#
# Borland C++ 2.0 with Application Frameworks, 5.25" 1200K version
#
# TODO: Finish unpacking it... then use it for a different project because this is NOT what Kye used! --GM
#

# NOTE: *SHOULD* be C:\BORLANDC, as BC.EXE gets modified by the installer if it isn't. (or at least it does with Borland C++ 3.0)
DSTDIR_BCP20AF:=target/root20/BORLANDC/

SRCDIR_BCP20AF_DISKS:=packages/bcp20af/
DISK_BCP20AF_01:=README OWLLIB.CA2 TD.CA2 WHELP.CA2 WHELP.CA3 README.COM FILELIST.DOC DISK1.DSK INSTALL.EXE UNZIP.EXE INSTALL.PIF CALC.ZIP CLASSINC.ZIP CLASSSRC.ZIP DLOBJ.ZIP INCLUDE.ZIP READOWL.ZIP READTV.ZIP THELP.ZIP WLOBJ.ZIP WMOBJ.ZIP WSOBJ.ZIP
DISK_BCP20AF_02:=CMDLINE.CA1 WBIN.CA1 BIN.CA2 CMDLINE.CA2 DISK2.DSK BGI.ZIP CLASSBLD.ZIP CURSOR.ZIP MANUAL.ZIP OWLSRC.ZIP
DISK_BCP20AF_03:=BIN.CA1 WBIN.CA2 DISK3.DSK BCC.ZIP BONK.ZIP CHAPXMPL.ZIP EXAMPLES.ZIP FILEAPP.ZIP MFILEAPP.ZIP MMACROS.ZIP PROGTALK.ZIP STARTUP.ZIP TDWEXMPL.ZIP TVINC.ZIP
DISK_BCP20AF_04:=OWLLIB.CA1 BC.CA2 BC.CA3 DISK4.DSK CLASSEXM.ZIP IDE.ZIP
DISK_BCP20AF_05:=BC.CA1 WHELP.CA1 DISK5.DSK CLIB.ZIP SYSINFO.ZIP TAEXMPL1.ZIP TVSRC.ZIP WEXAMPLE.ZIP
DISK_BCP20AF_06:=DISK6.DSK HELPTNT.ZIP LLIB.ZIP MANTNT.ZIP MLIB.ZIP OWL.ZIP OWLDEMOS.ZIP OWLDOC.ZIP OWLINC.ZIP TAEXMPL2.ZIP TVDEMOS.ZIP TVLIB.ZIP WINLIB.ZIP
DISK_BCP20AF_07:=TD.CA1 DISK7.DSK TDH386.SYS CHECKERS.ZIP DOC.ZIP GDIDEMO.ZIP HLIB.ZIP SLIB.ZIP TCALC.ZIP TPROF.ZIP TTT.ZIP TVHELP.ZIP WINCLUDE.ZIP
DISK_BCP20AF_08:=DISK8.DSK PAINT.ZIP STEPS.ZIP TASM.ZIP TDUTIL.ZIP TDW.ZIP TFEXMPL.ZIP TVDDEMOS.ZIP XLIB.ZIP
DISK_BCP20AF_09:=DISK9.DSK CLASSLIB.ZIP TDEXMPL.ZIP BGIKIT/README.1ST BGIKIT/BGIDRV/MAKEFILE BGIKIT/BGIDRV/DEBVECT.ASM BGIKIT/BGIDRV/BUILD.BAT BGIKIT/BGIDRV/DEBUG.BGI BGIKIT/BGIDRV/BH.C BGIKIT/BGIDRV/DEBDEMO.C BGIKIT/BGIDRV/DEBUG.C BGIKIT/BGIDRV/BGI.DOC BGIKIT/BGIDRV/BH.EXE BGIKIT/BGIDRV/DEBDEMO.EXE BGIKIT/BGIDRV/EXETOBIN.EXE BGIKIT/BGIDRV/DEVICE.INC BGIKIT/BGIDRV/F_DEBUG.OBJ BGIKIT/BGIDRV/N_DEBUG.OBJ BGIKIT/BGIFNT/DFONT.C BGIKIT/BGIFNT/FE.DOC BGIKIT/BGIFNT/DFONT.EXE BGIKIT/BGIFNT/FE.EXE BGIKIT/BGIFNT/FONT.H BGIKIT/FONTRUS/ARUS.CHR BGIKIT/FONTRUS/CYRBOLD.CHR BGIKIT/FONTRUS/CYRDRFT.CHR BGIKIT/FONTRUS/CYRGOTH.CHR BGIKIT/FONTRUS/CYRITAL.CHR BGIKIT/FONTRUS/EUROR.CHR BGIKIT/FONTRUS/LCOMR.CHR BGIKIT/FONTRUS/LITTR.CHR BGIKIT/FONTRUS/RLIT.CHR BGIKIT/FONTRUS/RTPL.CHR BGIKIT/FONTRUS/RTRI.CHR BGIKIT/FONTRUS/TRIPR.CHR BGIKIT/FONTRUS/TSCRR.CHR BGIKIT/FONTS/EURO.CHR BGIKIT/FONTS/GOTH.CHR BGIKIT/FONTS/LCOM.CHR BGIKIT/FONTS/LITT.CHR BGIKIT/FONTS/SANS.CHR BGIKIT/FONTS/SCRI.CHR BGIKIT/FONTS/SIMP.CHR BGIKIT/FONTS/TRIP.CHR BGIKIT/FONTS/TSCR.CHR BGIKIT/HERC/HERC.BGI BGIKIT/HERC/BGIDEMO.C BGIKIT/HERC/HERCBGI.DOC BGIKIT/HERC/BGIDEMO.PAS BGIKIT/HERC/HERCULES.PAS BGIKIT/HERC/HERCULES.TPU BGIKIT/VGA256/VGA256.BGI BGIKIT/VGA256/HSI.PAS BGIKIT/VGA256/VGADEMO.PAS BGIKIT/WORK/ARUS.CHR BGIKIT/WORK/CYRBOLD.CHR BGIKIT/WORK/CYRDRFT.CHR BGIKIT/WORK/CYRGOTH.CHR BGIKIT/WORK/CYRITAL.CHR BGIKIT/WORK/EURO.CHR BGIKIT/WORK/EUROR.CHR BGIKIT/WORK/GOTH.CHR BGIKIT/WORK/LCOM.CHR BGIKIT/WORK/LCOMR.CHR BGIKIT/WORK/LITT.CHR BGIKIT/WORK/LITTR.CHR BGIKIT/WORK/RLIT.CHR BGIKIT/WORK/RTPL.CHR BGIKIT/WORK/RTRI.CHR BGIKIT/WORK/SANS.CHR BGIKIT/WORK/SCRI.CHR BGIKIT/WORK/SIMP.CHR BGIKIT/WORK/TRIP.CHR BGIKIT/WORK/TRIPR.CHR BGIKIT/WORK/TSCR.CHR BGIKIT/WORK/TSCRR.CHR

EXTRACT_BCP20AF_DISKS:=\
	$(patsubst %,osdisks/bcp20a01/%,$(DISK_BCP20AF_01)) \
	$(patsubst %,osdisks/bcp20a02/%,$(DISK_BCP20AF_02)) \
	$(patsubst %,osdisks/bcp20a03/%,$(DISK_BCP20AF_03)) \
	$(patsubst %,osdisks/bcp20a04/%,$(DISK_BCP20AF_04)) \
	$(patsubst %,osdisks/bcp20a05/%,$(DISK_BCP20AF_05)) \
	$(patsubst %,osdisks/bcp20a06/%,$(DISK_BCP20AF_06)) \
	$(patsubst %,osdisks/bcp20a07/%,$(DISK_BCP20AF_07)) \
	$(patsubst %,osdisks/bcp20a08/%,$(DISK_BCP20AF_08)) \
	$(patsubst %,osdisks/bcp20a09/%,$(DISK_BCP20AF_09)) \
	#
MERGE_BCP20AF_DISKS:=\
	$(sort \
		$(patsubst %,osdisks/bcp20axx/%,$(DISK_BCP20AF_01)) \
		$(patsubst %,osdisks/bcp20axx/%,$(DISK_BCP20AF_02)) \
		$(patsubst %,osdisks/bcp20axx/%,$(DISK_BCP20AF_03)) \
		$(patsubst %,osdisks/bcp20axx/%,$(DISK_BCP20AF_04)) \
		$(patsubst %,osdisks/bcp20axx/%,$(DISK_BCP20AF_05)) \
		$(patsubst %,osdisks/bcp20axx/%,$(DISK_BCP20AF_06)) \
		$(patsubst %,osdisks/bcp20axx/%,$(DISK_BCP20AF_07)) \
		$(patsubst %,osdisks/bcp20axx/%,$(DISK_BCP20AF_08)) \
		$(patsubst %,osdisks/bcp20axx/%,$(DISK_BCP20AF_09)) \
	)

$(patsubst %,osdisks/bcp20a01/%,$(DISK_BCP20AF_01)) &: $(SRCDIR_BCP20AF_DISKS)disk01.img
	(install -D -d osdisks/bcpBIN/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp20a01/)
$(patsubst %,osdisks/bcp20a02/%,$(DISK_BCP20AF_02)) &: $(SRCDIR_BCP20AF_DISKS)disk02.img
	(install -D -d osdisks/bcp20a02/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp20a02/)
$(patsubst %,osdisks/bcp20a03/%,$(DISK_BCP20AF_03)) &: $(SRCDIR_BCP20AF_DISKS)disk03.img
	(install -D -d osdisks/bcp20a03/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp20a03/)
$(patsubst %,osdisks/bcp20a04/%,$(DISK_BCP20AF_04)) &: $(SRCDIR_BCP20AF_DISKS)disk04.img
	(install -D -d osdisks/bcp20a04/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp20a04/)
$(patsubst %,osdisks/bcp20a05/%,$(DISK_BCP20AF_05)) &: $(SRCDIR_BCP20AF_DISKS)disk05.img
	(install -D -d osdisks/bcp20a05/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp20a05/)
$(patsubst %,osdisks/bcp20a06/%,$(DISK_BCP20AF_06)) &: $(SRCDIR_BCP20AF_DISKS)disk06.img
	(install -D -d osdisks/bcp20a06/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp20a06/)
$(patsubst %,osdisks/bcp20a07/%,$(DISK_BCP20AF_07)) &: $(SRCDIR_BCP20AF_DISKS)disk07.img
	(install -D -d osdisks/bcp20a07/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp20a07/)
$(patsubst %,osdisks/bcp20a08/%,$(DISK_BCP20AF_08)) &: $(SRCDIR_BCP20AF_DISKS)disk08.img
	(install -D -d osdisks/bcp20a08/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp20a08/)
$(patsubst %,osdisks/bcp20a09/%,$(DISK_BCP20AF_09)) &: $(SRCDIR_BCP20AF_DISKS)disk09.img
	(install -D -d osdisks/bcp20a09/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp20a09/)

$(MERGE_BCP20AF_DISKS) &: $(EXTRACT_BCP20AF_DISKS)
	install -D -d osdisks/bcp20axx/
	cp -r osdisks/bcp20a01/* osdisks/bcp20axx/
	cp -r osdisks/bcp20a02/* osdisks/bcp20axx/
	cp -r osdisks/bcp20a03/* osdisks/bcp20axx/
	cp -r osdisks/bcp20a04/* osdisks/bcp20axx/
	cp -r osdisks/bcp20a05/* osdisks/bcp20axx/
	cp -r osdisks/bcp20a06/* osdisks/bcp20axx/
	cp -r osdisks/bcp20a07/* osdisks/bcp20axx/
	cp -r osdisks/bcp20a08/* osdisks/bcp20axx/
	cp -r osdisks/bcp20a09/* osdisks/bcp20axx/

# Archive merging
BCP20AF_SPLIT_ARCHIVES:=BC.ZIP BIN.ZIP CMDLINE.ZIP OWLLIB.ZIP TD.ZIP WBIN.ZIP WHELP.ZIP
MERGE_BCP20AF_ARCHIVES:=$(patsubst %,osdisks/bcp20axx/%,$(BCP20AF_SPLIT_ARCHIVES))
osdisks/bcp20axx/BC.ZIP: osdisks/bcp20a05/BC.CA1 osdisks/bcp20a04/BC.CA2 osdisks/bcp20a04/BC.CA3
	install -D -d osdisks/bcp20axx/
	(scripts/bccacat.sh $^ > $@.tmp) || (rm $@.tmp && false)
	mv $@.tmp $@
osdisks/bcp20axx/BIN.ZIP: osdisks/bcp20a03/BIN.CA1 osdisks/bcp20a02/BIN.CA2
	install -D -d osdisks/bcp20axx/
	(scripts/bccacat.sh $^ > $@.tmp) || (rm $@.tmp && false)
	mv $@.tmp $@
osdisks/bcp20axx/CMDLINE.ZIP: osdisks/bcp20a02/CMDLINE.CA1 osdisks/bcp20a02/CMDLINE.CA2
	install -D -d osdisks/bcp20axx/
	(scripts/bccacat.sh $^ > $@.tmp) || (rm $@.tmp && false)
	mv $@.tmp $@
osdisks/bcp20axx/OWLLIB.ZIP: osdisks/bcp20a04/OWLLIB.CA1 osdisks/bcp20a01/OWLLIB.CA2
	install -D -d osdisks/bcp20axx/
	(scripts/bccacat.sh $^ > $@.tmp) || (rm $@.tmp && false)
	mv $@.tmp $@
osdisks/bcp20axx/TD.ZIP: osdisks/bcp20a07/TD.CA1 osdisks/bcp20a01/TD.CA2
	install -D -d osdisks/bcp20axx/
	(scripts/bccacat.sh $^ > $@.tmp) || (rm $@.tmp && false)
	mv $@.tmp $@
osdisks/bcp20axx/WBIN.ZIP: osdisks/bcp20a02/WBIN.CA1 osdisks/bcp20a03/WBIN.CA2
	install -D -d osdisks/bcp20axx/
	(scripts/bccacat.sh $^ > $@.tmp) || (rm $@.tmp && false)
	mv $@.tmp $@
osdisks/bcp20axx/WHELP.ZIP: osdisks/bcp20a05/WHELP.CA1 osdisks/bcp20a01/WHELP.CA2 osdisks/bcp20a01/WHELP.CA3
	install -D -d osdisks/bcp20axx/
	(scripts/bccacat.sh $^ > $@.tmp) || (rm $@.tmp && false)
	mv $@.tmp $@

# Actually extracting files

# for A in $(echo $(echo -n osdisks/bcp20axx/*.ZIP) | sort); do echo "ARCHIVE_BCP20AF_$(echo -n $A | sed -e 's#\.ZIP##g' -e 's#.*/##g'):=$(echo $(unzip -Z -1 $A 2>/dev/null))"; done
BCP20AF_ARCHIVE_NAMES:=BC BCC BGI BIN BONK CALC CHAPXMPL CHECKERS CLASSBLD CLASSEXM CLASSINC CLASSLIB CLASSSRC CLIB CMDLINE CURSOR DLOBJ DOC EXAMPLES FILEAPP GDIDEMO HELPTNT HLIB IDE INCLUDE LLIB MANTNT MANUAL MFILEAPP MLIB MMACROS OWL OWLDEMOS OWLDOC OWLINC OWLLIB OWLSRC PAINT PROGTALK READOWL READTV SLIB STARTUP STEPS SYSINFO TAEXMPL1 TAEXMPL2 TASM TCALC TD TDEXMPL TDUTIL TDW TDWEXMPL TFEXMPL THELP TPROF TTT TVDDEMOS TVDEMOS TVHELP TVINC TVLIB TVSRC WBIN WEXAMPLE WHELP WINCLUDE WINLIB WLOBJ WMOBJ WSOBJ XLIB
BCP20AF_ARCHIVE_FILES:=$(patsubst %,osdisks/bcp20axx/%.ZIP,$(BCP20AF_ARCHIVE_NAMES))

# Initial empty list
BCP20AF_TARGETS:=

ARCHIVE_BCP20AF_BC:=BC.EXE BCX.EXE BCX.OVY
BCP20AF_TARGETS:=$(BCP20AF_TARGETS) $(patsubst %,$(DSTDIR_BCP20AF)BIN/%,$(ARCHIVE_BCP20AF_BC))
$(patsubst %,$(DSTDIR_BCP20AF)BIN/%,$(ARCHIVE_BCP20AF_BC)) &: osdisks/bcp20axx/BC.ZIP
	install -D -d $(DSTDIR_BCP20AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP20AF)BIN/ $<

ARCHIVE_BCP20AF_BCC:=BCCX.EXE BCCX.OVY
BCP20AF_TARGETS:=$(BCP20AF_TARGETS) $(patsubst %,$(DSTDIR_BCP20AF)BIN/%,$(ARCHIVE_BCP20AF_BCC))
$(patsubst %,$(DSTDIR_BCP20AF)BIN/%,$(ARCHIVE_BCP20AF_BCC)) &: osdisks/bcp20axx/BCC.ZIP
	install -D -d $(DSTDIR_BCP20AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP20AF)BIN/ $<

ARCHIVE_BCP20AF_BGI:=ATT.BGI BGIDEMO.C BGIOBJ.EXE CGA.BGI EGAVGA.BGI GOTH.CHR HERC.BGI IBM8514.BGI LITT.CHR PC3270.BGI SANS.CHR TRIP.CHR
BCP20AF_TARGETS:=$(BCP20AF_TARGETS) $(patsubst %,$(DSTDIR_BCP20AF)BIN/%,$(ARCHIVE_BCP20AF_BGI))
$(patsubst %,$(DSTDIR_BCP20AF)BIN/%,$(ARCHIVE_BCP20AF_BGI)) &: osdisks/bcp20axx/BGI.ZIP
	install -D -d $(DSTDIR_BCP20AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP20AF)BIN/ $<

ARCHIVE_BCP20AF_BIN:=BCRTL.DLL BWCC.DLL EMSTEST.COM GREP.COM OBJXREF.COM OWL.DLL OWL.TDS THELP.COM TKERNEL.EXE TKINST.EXE TLIB.EXE TOUCH.COM TRANCOPY.EXE TRIGRAPH.EXE
BCP20AF_TARGETS:=$(BCP20AF_TARGETS) $(patsubst %,$(DSTDIR_BCP20AF)BIN/%,$(ARCHIVE_BCP20AF_BIN))
$(patsubst %,$(DSTDIR_BCP20AF)BIN/%,$(ARCHIVE_BCP20AF_BIN)) &: osdisks/bcp20axx/BIN.ZIP
	install -D -d $(DSTDIR_BCP20AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP20AF)BIN/ $<

ARCHIVE_BCP20AF_BONK:=BOARD.BMP BOARD2.BMP BONK.CPP BONK.H BONK.PRJ BONK.RC BONK2.RC CRITTER.ICO CRITTER2.ICO DEAD.BMP DEAD2.BMP GAMEOVE2.BMP GAMEOVER.BMP LIVE.BMP LIVE2.BMP MAKEFILE MALET.CUR MALET2.CUR MALETDO2.CUR MALETDOW.CUR
BCP20AF_TARGETS:=$(BCP20AF_TARGETS) $(patsubst %,$(DSTDIR_BCP20AF)OWL/EXAMPLES/BONK/%,$(ARCHIVE_BCP20AF_BONK))
$(patsubst %,$(DSTDIR_BCP20AF)OWL/EXAMPLES/BONK/%,$(ARCHIVE_BCP20AF_BONK)) &: osdisks/bcp20axx/BONK.ZIP
	install -D -d $(DSTDIR_BCP20AF)OWL/EXAMPLES/BONK/
	unzip -DD -o -d $(DSTDIR_BCP20AF)OWL/EXAMPLES/BONK/ $<

ARCHIVE_BCP20AF_CALC:=CALC.CPP CALC.ICO CALC.PRJ CALC.RC MAKEFILE
BCP20AF_TARGETS:=$(BCP20AF_TARGETS) $(patsubst %,$(DSTDIR_BCP20AF)OWL/EXAMPLES/CALC/%,$(ARCHIVE_BCP20AF_CALC))
$(patsubst %,$(DSTDIR_BCP20AF)OWL/EXAMPLES/CALC/%,$(ARCHIVE_BCP20AF_CALC)) &: osdisks/bcp20axx/CALC.ZIP
	install -D -d $(DSTDIR_BCP20AF)OWL/EXAMPLES/CALC/
	unzip -DD -o -d $(DSTDIR_BCP20AF)OWL/EXAMPLES/CALC/ $<

ARCHIVE_BCP20AF_CHAPXMPL:=ADD.ASM ADDPRO.PRO ASMPROC.ASM AVERAGE.ASM CALCAVG.CPP CALLCT.CPP CNTWORDS.ASM COUNT.ASM COUNTLG.ASM DOTOTAL.ASM DOTOTAL2.ASM ENVSTR.ASM ENVTEST.PAS FROM_ASM.ASM FROM_NEW.ASM FUNC.PRO HELLO.ASM HELLO2.ASM HELLOPRN.ASM HEXSTR.ASM HEXTEST.PAS IDLEXMPL.ASM IFUNC.ASM MAIN.ASM MASEXMPL.ASM MULT_C&D.ASM MYASM.ASM MYPROLOG.PRO PLUSONE.C PRIMES.ASM REVERSE.ASM SAMPLE.PAS SCROL.ASM SCROLLH.PRO SHOWMESS.PRO SHOWNEW.PRO SHOWTOT.CPP SQRETBLE.C SQRTBLE2.C STDSEG.ASM STRINGUP.C SUB1.ASM TOGLFLAG.ASM TOGLFLAG.C TSAMPLE.PAS XCHANGE.ASM XCHANGE.PAS
ARCHIVE_BCP20AF_CHECKERS:=BLACKKNG.BMP BLACKMAN.BMP BOARD.CPP BOARD.H CHECKERS.CPP CHECKERS.H CHECKERS.ICO CHECKERS.PRJ CHECKERS.RC HAND.CUR HANDPC.CUR INFO.CPP INFO.H MAKEFILE REDKING.BMP REDMAN.BMP
ARCHIVE_BCP20AF_CLASSBLD:=BUILDCL.BAT
ARCHIVE_BCP20AF_CLASSEXM:=DIRECTRY.CPP DIRECTRY.H DIRECTRY.PRJ FILEDATA.CPP FILEDATA.H LOOKUP.CPP LOOKUP.PRJ QUEUETST.CPP QUEUETST.PRJ REVERSE.CPP REVERSE.PRJ STRNGMAX.CPP STRNGMAX.PRJ TESTDIR.CPP
ARCHIVE_BCP20AF_CLASSINC:=ABSTARRY.H ARRAY.H ASSOC.H BAG.H CLSDEFS.H CLSTYPES.H COLLECT.H CONTAIN.H DBLLIST.H DEQUE.H DICT.H DLSTELEM.H ERREXIT.H HASHTBL.H LDATE.H LIST.H LSTELEM.H LTIME.H OBJECT.H QUEUE.H RESOURCE.H SET.H SORTABLE.H SORTARRY.H STACK.H STRNG.H
ARCHIVE_BCP20AF_CLASSLIB:=TCLASSDL.LIB TCLASSS.LIB TCLASSWL.LIB TCLASSWM.LIB TCLASSWS.LIB
ARCHIVE_BCP20AF_CLASSSRC:=ABSTARRY.CPP ARRAY.CPP ASSOC.CPP BAG.CPP COLLECT.CPP CONTAIN.CPP DBLLIST.CPP DEQUE.CPP DICT.CPP ERREXIT.CPP HASHTBL.CPP LDATE.CPP LIST.CPP LTIME.CPP MAKEFILE OBJECT.CPP QUEUE.CPP SET.CPP SORTABLE.CPP SORTARRY.CPP STACK.CPP STRNG.CPP
ARCHIVE_BCP20AF_CLIB:=C0C.OBJ C0DC.OBJ C0FC.OBJ CC.LIB MATHC.LIB OLDSTRMC.LIB

ARCHIVE_BCP20AF_CMDLINE:=BCC.EXE CPP.EXE MAKE.EXE TLINK.EXE TLINKX.EXE TLINKX.OVY
BCP20AF_TARGETS:=$(BCP20AF_TARGETS) $(patsubst %,$(DSTDIR_BCP20AF)BIN/%,$(ARCHIVE_BCP20AF_CMDLINE))
$(patsubst %,$(DSTDIR_BCP20AF)BIN/%,$(ARCHIVE_BCP20AF_CMDLINE)) &: osdisks/bcp20axx/CMDLINE.ZIP
	install -D -d $(DSTDIR_BCP20AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP20AF)BIN/ $<

ARCHIVE_BCP20AF_CURSOR:=CURSOR.CPP CURSOR.DEF CURSOR.H CURSOR.ICO CURSOR.PRJ CURSOR.RC MAKEFILE
ARCHIVE_BCP20AF_DLOBJ:=VERSION.OBJ
ARCHIVE_BCP20AF_DOC:=DEFAULTS.TEM HELPME!.DOC OLDSTR.DOC UTIL.DOC WINPRIMR.DOC
ARCHIVE_BCP20AF_EXAMPLES:=BARCHART.C CIRCLE.CPP CIRCLE.PRJ CPASDEMO.C CPASDEMO.PAS CTOPAS.CFG CTOPAS.PRJ DCOPY.CPP DEF.CPP DEF.H DEF2.CPP DEF2.H DICTION.CPP DICTION.H DYNPOINT.CPP DYNPOINT.PRJ EX1.CPP EX2.CPP EX3.CPP EX4.CPP EX5.CPP EX5.PRJ EX6.CPP EX6.PRJ EX7.CPP EX7.PRJ EX8.CPP EX8.PRJ EX9.CPP EX9.PRJ FIGDEMO.CPP FIGDEMO.PRJ FIGURES.CPP FIGURES.H FILTER.H GETOPT.C GREP2MSG.C HELLO.C IMPL2MSG.C LIST.CPP LIST.H LIST2.CPP LIST2.H LISTDEMO.CPP LISTDEMO.PRJ MCIRCLE.CPP MCIRCLE.PRJ PIXEL.CPP PIXEL.PRJ POINT.CPP POINT.H POINT2.CPP RC2MSG.C STACK.CPP STACK.H STACK2.CPP STACK2.H STRING.CPP TASM2MSG.C VCIRC.CPP VCIRC.PRJ VPOINT.CPP VPOINT.H XSTRING.CPP
ARCHIVE_BCP20AF_FILEAPP:=FILEAPP.CPP FILEAPP.PRJ FILEAPP.RC MAKEFILE
ARCHIVE_BCP20AF_GDIDEMO:=ARTY.CPP ARTY.H ARTYPRIV.H BACKGRND.BMP BITBLT.CPP BITBLT.H DEMOBASE.H FONT.CPP FONT.H GDIDEMO.CPP GDIDEMO.PRJ GDIDEMO.RC LINE.CPP LINE.H MAKEFILE MONOSHIP.BMP SHIP.BMP
ARCHIVE_BCP20AF_HELPTNT:=HELPME!.TNT
ARCHIVE_BCP20AF_HLIB:=C0FH.OBJ C0H.OBJ CH.LIB MATHH.LIB OLDSTRMH.LIB
ARCHIVE_BCP20AF_IDE:=BCINST.EXE GREP2MSG.EXE PRJ2MAK.EXE PRJCFG.EXE PRJCNVT.EXE TASM2MSG.EXE TEMC.EXE

ARCHIVE_BCP20AF_INCLUDE:=ALLOC.H ASSERT.H BCD.H BIOS.H COMPLEX.H CONIO.H CTYPE.H DIR.H DIRECT.H DOS.H ERRNO.H FCNTL.H FLOAT.H FSTREAM.H GENERIC.H GRAPHICS.H IO.H IOMANIP.H IOSTREAM.H LIMITS.H LOCALE.H MALLOC.H MATH.H MEM.H MEMORY.H NEW.H PROCESS.H SEARCH.H SETJMP.H SHARE.H SIGNAL.H STDARG.H STDDEF.H STDIO.H STDIOSTR.H STDLIB.H STREAM.H STRING.H STRSTREA.H TIME.H VALUES.H VARARGS.H _DEFS.H
ARCHIVE_BCP20AF_INCLUDE_SYS:=STAT.H TIMEB.H TYPES.H
BCP20AF_TARGETS:=$(BCP20AF_TARGETS) $(patsubst %,$(DSTDIR_BCP20AF)INCLUDE/%,$(ARCHIVE_BCP20AF_INCLUDE)) $(patsubst %,$(DSTDIR_BCP20AF)INCLUDE/SYS/%,$(ARCHIVE_BCP20AF_INCLUDE_SYS))
$(patsubst %,$(DSTDIR_BCP20AF)INCLUDE/%,$(ARCHIVE_BCP20AF_INCLUDE)) &: osdisks/bcp20axx/INCLUDE.ZIP
	install -D -d $(DSTDIR_BCP20AF)INCLUDE/
	unzip -DD -o -d $(DSTDIR_BCP20AF)INCLUDE/ $< $(ARCHIVE_BCP20AF_INCLUDE)
$(patsubst %,$(DSTDIR_BCP20AF)INCLUDE/SYS/%,$(ARCHIVE_BCP20AF_INCLUDE_SYS)) &: osdisks/bcp20axx/INCLUDE.ZIP
	install -D -d $(DSTDIR_BCP20AF)INCLUDE/SYS/
	unzip -DD -o -d $(DSTDIR_BCP20AF)INCLUDE/SYS/ $< $(ARCHIVE_BCP20AF_INCLUDE_SYS)

ARCHIVE_BCP20AF_LLIB:=C0DL.OBJ C0FL.OBJ C0L.OBJ CL.LIB CRTLL.LIB MATHL.LIB OLDSTRML.LIB
ARCHIVE_BCP20AF_MANTNT:=MANUAL.TNT
ARCHIVE_BCP20AF_MANUAL:=BASIC.DOC PROLOG.DOC TCREF.DOC
ARCHIVE_BCP20AF_MFILEAPP:=MAKEFILE MFILEAPP.CPP MFILEAPP.H MFILEAPP.PRJ MFILEAPP.RC
ARCHIVE_BCP20AF_MLIB:=C0DM.OBJ C0FM.OBJ C0M.OBJ CM.LIB MATHM.LIB OLDSTRMM.LIB
ARCHIVE_BCP20AF_MMACROS:=BIOS.INC DOS.INC KBD.INC MBIOS.MAC MDOS.MAC MMACROS.MAC
ARCHIVE_BCP20AF_OWL:=BUILDOWL.BAT OWLTHELP.OWH OWLWHELP.HLP
ARCHIVE_BCP20AF_OWLDEMOS:=BSCRLAPP.CPP BSCRLAPP.PRJ BSCRLAPP.RC BTNTEST.CPP BTNTEST.PRJ BUILD.BAT CALLDLL.CPP CALLDLL.H CALLDLL.PRJ CALLDLL.RC CBOXTEST.CPP CBOXTEST.PRJ CBXTTEST.CPP CBXTTEST.PRJ CCTLTEST.CPP CCTLTEST.H CCTLTEST.PRJ CCTLTEST.RC CDLGDLL.CPP CDLGDLL.DEF CDLGDLL.H CDLGDLL.PRJ CDLGDLL.RC COLORDLG.CPP COLORDLG.DLG COLORDLG.H COLORDLG.RCH CURSAPP.CPP CURSAPP.PRJ DCTLTEST.CPP DCTLTEST.H DCTLTEST.PRJ DCTLTEST.RC DIALTEST.CPP DIALTEST.H DIALTEST.PRJ DIALTEST.RC DLLHELLO.CPP DLLHELLO.H DLLHELLO.PRJ EDITAPP.CPP EDITAPP.PRJ EDITAPP.RC EDITTEST.CPP EDITTEST.PRJ EWNDTEST.CPP EWNDTEST.H EWNDTEST.PRJ EWNDTEST.RC GBOXTEST.CPP GBOXTEST.PRJ HELLOAPP.CPP HELLOAPP.PRJ INSTTEST.CPP INSTTEST.PRJ LBOXTEST.CPP LBOXTEST.PRJ LBXTTEST.CPP LBXTTEST.PRJ MAKEFILE MAKEFILE.INC MDIAPP.CPP MDIAPP.PRJ MDIAPP.RC MDITEST.CPP MDITEST.H MDITEST.PRJ MDITEST.RC MLBXTTST.CPP MLBXTTST.PRJ NOTITEST.CPP NOTITEST.H NOTITEST.PRJ NOTITEST.RC PALTEST.CPP PALTEST.DLG PALTEST.H PALTEST.PRJ PALTEST.RC POPUP.CPP POPUP.PRJ POPUP.RC SBARTEST.CPP SBARTEST.PRJ SCRIBAPP.CPP SCRIBAPP.PRJ SCROLAPP.CPP SCROLAPP.PRJ STATTEST.CPP STATTEST.PRJ TRANTEST.CPP TRANTEST.H TRANTEST.PRJ TRANTEST.RC USECDLL.CPP USECDLL.H USECDLL.PRJ USECDLL.RC USECDLL2.CPP USECDLL2.H USECDLL2.RC VDLGAPP.CPP VDLGAPP.PRJ VDLGAPP.RC
ARCHIVE_BCP20AF_OWLDOC:=BWCC-OWL.DOC BWCCAPI.DOC BWCCSTYL.DOC DLL.DOC HELPME!.DOC MANUAL.DOC
ARCHIVE_BCP20AF_OWLINC:=APPDICT.H APPLICAT.H BBUTTON.H BCHKBOX.H BDIVIDER.H BGRPBOX.H BRADIO.H BSTATBMP.H BSTATIC.H BUTTON.H BWCC.H BWINDOW.H CHECKBOX.H COMBOBOX.H CONTROL.H DIALOG.H EDIT.H EDITACC.RC EDITMENU.RC EDITWND.H FILEACC.RC FILEDIAL.DLG FILEDIAL.H FILEMENU.RC FILEWND.H GROUPBOX.H INPUTDIA.DLG INPUTDIA.H LISTBOX.H MDI.H MODULE.H OBJSTRM.H OWL.H OWLDEFS.H OWLRC.H RADIOBUT.H SAFEPOOL.H SCROLLBA.H SCROLLER.H STATIC.H STDWNDS.DLG TCOLLECT.H WINDOBJ.H WINDOW.H
ARCHIVE_BCP20AF_OWLLIB:=BWCC.LIB OWL.DEF OWL.LIB OWLDLL.DEF OWLWL.LIB OWLWM.LIB OWLWS.LIB SALLOCWC.LIB SALLOCWL.LIB SALLOCWM.LIB SALLOCWS.LIB
ARCHIVE_BCP20AF_OWLSRC:=APPDICT.CPP APPLICAT.CPP BBUTTON.CPP BCHKBOX.CPP BDIVIDER.CPP BGRPBOX.CPP BRADIO.CPP BSTATBMP.CPP BSTATIC.CPP BUTTON.CPP BWINDOW.CPP CHECKBOX.CPP COMBOBOX.CPP CONTROL.CPP DD.ASM DIALOG.CPP DLLREF.CPP EDIT.CPP EDITWND.CPP FILEDIAL.CPP FILEWND.CPP GROUPBOX.CPP INPUTDIA.CPP LISTBOX.CPP MAKEFILE MDICLIEN.CPP MDIFRAME.CPP MODULE.CPP OBJSTRM.CPP OWL.CPP OWLDLL.DEF OWLMATH.CPP RADIOBUT.CPP SAFEPOOL.CPP SCROLLBA.CPP SCROLLER.CPP STATIC.CPP SWINDOBJ.CPP TCOLLECT.CPP TSORTCOL.CPP WINDOBJ.CPP WINDOW.CPP
ARCHIVE_BCP20AF_PAINT:=ELLIPSE.CUR ELLIPSE.ICO FELLIPSE.CUR FELLIPSE.ICO FILL.CUR FILL.ICO FRECT.CUR FRECT.ICO MAKEFILE OWLPAINT.ICO PAINT.CPP PAINT.PRJ PAINT.RC PEN.CUR PEN.ICO RECT.CUR RECT.ICO
ARCHIVE_BCP20AF_PROGTALK:=DDECLIEN.CPP DDECLIEN.H MAKEFILE PROGTALK.CPP PROGTALK.H PROGTALK.PRJ PROGTALK.RC
ARCHIVE_BCP20AF_READOWL:=README
ARCHIVE_BCP20AF_READTV:=README

ARCHIVE_BCP20AF_SLIB:=C0DS.OBJ C0FS.OBJ C0FT.OBJ C0S.OBJ C0T.OBJ CS.LIB MATHS.LIB OLDSTRMS.LIB
BCP20AF_TARGETS:=$(BCP20AF_TARGETS) $(patsubst %,$(DSTDIR_BCP20AF)LIB/%,$(ARCHIVE_BCP20AF_SLIB))
$(patsubst %,$(DSTDIR_BCP20AF)LIB/%,$(ARCHIVE_BCP20AF_SLIB)) &: osdisks/bcp20axx/SLIB.ZIP
	install -D -d $(DSTDIR_BCP20AF)LIB/
	unzip -DD -o -d $(DSTDIR_BCP20AF)LIB/ $<

ARCHIVE_BCP20AF_STARTUP:=BUILD-C0.BAT C0.ASM C0D.ASM C0W.ASM RULES.ASI
ARCHIVE_BCP20AF_STEPS:=HELPWIND.CPP HELPWIND.DEF HELPWIND.H HELPWIND.RC MAKEFILE STEP1.CPP STEP1.PRJ STEP10.CPP STEP10.PRJ STEP2.CPP STEP2.PRJ STEP3.CPP STEP3.PRJ STEP4.CPP STEP4.PRJ STEP5.CPP STEP5.PRJ STEP6.CPP STEP6.PRJ STEP7.CPP STEP7.PRJ STEP8.CPP STEP8.PRJ STEP9.CPP STEP9.PRJ STEPS.DEF STEPS.H STEPS.RC
ARCHIVE_BCP20AF_SYSINFO:=MAKEFILE SYSINFO.CPP SYSINFO.H SYSINFO.PRJ SYSINFO.RC
ARCHIVE_BCP20AF_TAEXMPL1:=BIOS.INC BIOSMAC.DOC DEMO1.BAT DOS.INC DOSMAC.DOC IASCIIZS.ASM IBIOS.MAC IBYTECPY.ASM IDELCHAR.ASM IDOS.INC IDOS.MAC IEXECDOS.ASM IFINDBYT.ASM IFINDFIL.ASM IFINDREP.ASM ILOCSTRG.ASM IMACROS.MAC IPARAM.ASM IPARSEFN.ASM ISKPWHIT.ASM IWHEREIS.ASM IWHGLOBL.INC IWRITEPS.ASM KBD.INC WHEREIS.DOC WHEREIS.MAK WHUSAGE.INC
ARCHIVE_BCP20AF_TAEXMPL2:=CONVERT1.INC CONVERT2.INC DEMO2.BAT DEMO3.BAT FILT.ASM FILT.DOC FILT.MAK FILT.RSP GLOBALS.INC OBYTEHI.ASM OBYTELOW.ASM OBYTENRM.ASM OCMDNUM.ASM OERREXIT.ASM OFCREATE.ASM OFILALOC.ASM OFILCLOS.ASM OFILEFIL.ASM OFILFREE.ASM OFILREAD.ASM OFILWRIT.ASM OFLFLUSH.ASM OFOPENR.ASM OFOPENW.ASM OLOCASE.ASM OPARSCMD.ASM OPRCBYTE.ASM OPROCDOC.ASM OPROCLIN.ASM OSETOPTN.ASM OSPACES.ASM OSTORSPC.ASM OSTORTAB.ASM OTABCLR.ASM OTABNEXT.ASM OTABRSET.ASM OTABSET.ASM OUPCASE.ASM SHOW87.ASM SHOW87.DOC VIDEO1.INC VIDEO2.INC
ARCHIVE_BCP20AF_TASM:=DPMILOAD.EXE GREP.COM MAKE.EXE OBJXREF.COM TASM.EXE TASMX.EXE TCREF.EXE TLIB.EXE TLINK.EXE TOUCH.COM
ARCHIVE_BCP20AF_TCALC:=TCALC.C TCALC.DOC TCALC.H TCALC.PRJ TCDISPLY.C TCINPUT.C TCOMMAND.C TCPARSER.C TCUTIL.C
ARCHIVE_BCP20AF_TD:=TD.EXE TD286.EXE TD386.EXE
ARCHIVE_BCP20AF_TDEXMPL:=TCDEMO.C TCDEMO.EXE TCDEMOB.C TCDEMOB.EXE TPDEMO.EXE TPDEMO.PAS TPDEMOB.EXE TPDEMOB.PAS
ARCHIVE_BCP20AF_TDUTIL:=TD286INS.EXE TDCONVRT.EXE TDDEV.EXE TDHELP.TDH TDINST.EXE TDMAP.EXE TDMEM.EXE TDNMI.COM TDPACK.EXE TDREMOTE.EXE TDRF.EXE TDSTRIP.EXE TDUMP.EXE
ARCHIVE_BCP20AF_TDW:=TDW.EXE TDWHELP.TDH WINDEBUG.DLL WREMOTE.EXE WRSETUP.EXE
ARCHIVE_BCP20AF_TDWEXMPL:=BCWDEMO.C BCWDEMO.DEF BCWDEMO.EXE BCWDEMO.H BCWDEMO.ICO BCWDEMO.PRJ BCWDEMO.RC BCWDEMOA.C BCWDEMOA.EXE BCWDEMOA.PRJ BCWDEMOB.C BCWDEMOB.EXE BCWDEMOB.PRJ
ARCHIVE_BCP20AF_TFEXMPL:=CALLTEST.C CALLTEST.EXE OVRDEMO.EXE OVRDEMO.OVR OVRDEMO.PAS OVRDEMO1.PAS OVRDEMO2.PAS PLOST.C PLOST.EXE PLOSTPAS.EXE PLOSTPAS.PAS PRIME0.C PRIME0.EXE PRIME0PA.EXE PRIME0PA.PAS PRIME1.C PRIME1.EXE PRIME1PA.EXE PRIME1PA.PAS PRIME2.C PRIME2.EXE PRIME2PA.EXE PRIME2PA.PAS PRIME3.C PRIME3.EXE PRIME3PA.EXE PRIME3PA.PAS PRIME4.C PRIME4.EXE PRIME4PA.EXE PRIME4PA.PAS PRIME5.C PRIME5.EXE PRIME5PA.EXE PRIME5PA.PAS PRIME6.C PRIME6.EXE PRIME6PA.EXE PRIME6PA.PAS PTOLL.C PTOLL.EXE PTOLLPAS.EXE PTOLLPAS.PAS
ARCHIVE_BCP20AF_THELP:=TASM.TAH THELP.COM
ARCHIVE_BCP20AF_TPROF:=TF386.EXE TFHELP.TFH TFINST.EXE TFREMOTE.EXE TPROF.EXE
ARCHIVE_BCP20AF_TTT:=MAKEFILE TTT.CPP TTT.H TTT.ICO TTT.PRJ TTT.RC
ARCHIVE_BCP20AF_TVDDEMOS:=TVG17B.CPP TVG17B.PRJ TVGUID01.CPP TVGUID01.PRJ TVGUID02.CPP TVGUID02.PRJ TVGUID03.CPP TVGUID03.PRJ TVGUID04.CPP TVGUID04.PRJ TVGUID05.CPP TVGUID05.PRJ TVGUID06.CPP TVGUID06.PRJ TVGUID07.CPP TVGUID07.PRJ TVGUID08.CPP TVGUID08.PRJ TVGUID09.CPP TVGUID09.PRJ TVGUID10.CPP TVGUID10.PRJ TVGUID11.CPP TVGUID11.PRJ TVGUID12.CPP TVGUID12.PRJ TVGUID13.CPP TVGUID13.PRJ TVGUID14.CPP TVGUID14.PRJ TVGUID15.CPP TVGUID15.PRJ TVGUID16.CPP TVGUID16.PRJ TVGUID17.CPP TVGUID17.PRJ TVGUID18.CPP TVGUID18.PRJ TVGUID19.CPP TVGUID19.PRJ TVGUID20.CPP TVGUID20.PRJ TVGUID21.CPP TVGUID21.PRJ
ARCHIVE_BCP20AF_TVDEMOS:=ASCII.CPP ASCII.H CALC.CPP CALC.H CALENDAR.CPP CALENDAR.H DATACOLL.CPP DATACOLL.H DEMOHELP.H DEMOHELP.HLP FIELDS.CPP FIELDS.H FILEVIEW.CPP FILEVIEW.H FILEVIEW.PRJ FORMCMDS.H FORMS.CPP FORMS.H FVIEWER.CPP GADGETS.CPP GADGETS.H GENFORM.CPP GENFORM.RSP GENFORMS.BAT GENPARTS.H GENPHONE.H GRAPHAPP.CPP GRAPHAPP.H HELLO.CPP HELLO.PRJ LISTDLG.CPP LISTDLG.H MOUSEDLG.CPP MOUSEDLG.H PUZZLE.CPP PUZZLE.H TVBGI.CPP TVBGI.H TVBGI.PRJ TVCMDS.H TVDEMO.H TVDEMO.PRJ TVDEMO1.CPP TVDEMO2.CPP TVDEMO3.CPP TVEDIT.H TVEDIT.PRJ TVEDIT1.CPP TVEDIT2.CPP TVEDIT3.CPP TVFORMS.CPP TVFORMS.PRJ TVTXTDMO.CPP TVTXTDMO.PRJ
ARCHIVE_BCP20AF_TVHELP:=DEMOHELP.TXT HELP.CPP TVHC.CPP TVHC.EXE TVHC.H TVHC.PRJ
ARCHIVE_BCP20AF_TVINC:=APP.H BUFFERS.H COLORSEL.H CONFIG.H DIALOGS.H DRAWBUF.H EDITORS.H HELP.H MENUS.H MSGBOX.H OBJECTS.H RESOURCE.H STDDLG.H SYSTEM.H TEXTVIEW.H TKEYS.H TOBJSTRM.H TTYPES.H TV.H TVOBJS.H UTIL.H VIEWS.H
ARCHIVE_BCP20AF_TVLIB:=TV.LIB
ARCHIVE_BCP20AF_TVSRC:=BUILD.BAT COLORSEL.CPP DRIVERS.CPP DRIVERS2.CPP EDITS.ASM EDITSTAT.CPP FRAMELIN.ASM GENINC.CPP GRP.CPP HISTLIST.CPP MAPCOLOR.CPP MENU.CPP MISC.CPP MSGBOX.CPP NEW.CPP NEWSTR.CPP NMBKGRND.CPP NMBUTTON.CPP NMCHDRDL.CPP NMCHKBOX.CPP NMCLRSEL.CPP NMCLUSTR.CPP NMCOLLCT.CPP NMDIALOG.CPP NMDIRBOX.CPP NMDIRCOL.CPP NMDSKTOP.CPP NMEDITOR.CPP NMFILCOL.CPP NMFILDLG.CPP NMFILLST.CPP NMFRAME.CPP NMGROUP.CPP NMHIST.CPP NMINPTLN.CPP NMLABEL.CPP NMLSTBOX.CPP NMLSTVWR.CPP NMMNUBAR.CPP NMMNUBOX.CPP NMMNUVW.CPP NMPRMTXT.CPP NMRBTNS.CPP NMRESCOL.CPP NMSCOLL.CPP NMSCRBAR.CPP NMSCROLL.CPP NMSTCTXT.CPP NMSTDDLG.CPP NMSTLINE.CPP NMSTRCOL.CPP NMSTRLST.CPP NMVIEW.CPP NMWINDOW.CPP PALETTE.CPP SBKGRND.CPP SBUTTON.CPP SCHDRDLG.CPP SCHECKBO.CPP SCLRSEL.CPP SCLUSTER.CPP SDESKTOP.CPP SDIALOG.CPP SDIRCOLL.CPP SDIRLIST.CPP SEDITORS.CPP SFILCOLL.CPP SFILDLG.CPP SFILELST.CPP SFINFPNE.CPP SFRAME.CPP SGROUP.CPP SHISTORY.CPP SINPUTLI.CPP SLABEL.CPP SLISTBOX.CPP SLSTVIEW.CPP SMENUBAR.CPP SMENUBOX.CPP SMNUVIEW.CPP SRADIOBU.CPP SRESCOLL.CPP SSCRLBAR.CPP SSCROLLE.CPP SSTATICT.CPP SSTATUSL.CPP SSTRCOLL.CPP SSTRLST.CPP STDDLG.CPP STRMSTAT.CPP SVIEW.CPP SWAPST.ASM SWINDOW.CPP SYSERR.CPP SYSINT.ASM TAPPLICA.CPP TBKGRND.CPP TBUTTON.CPP TCHDRDLG.CPP TCHECKBO.CPP TCLUSTER.CPP TCMDSET.CPP TCOLLECT.CPP TDESKTOP.CPP TDIALOG.CPP TDIRCOLL.CPP TDIRLIST.CPP TEDITOR1.CPP TEDITOR2.CPP TEDITWND.CPP TEVENT.CPP TEXTVIEW.CPP TFILDLG.CPP TFILECOL.CPP TFILEDTR.CPP TFILLIST.CPP TFRAME.CPP TGRMV.ASM TGROUP.CPP THISTORY.CPP THISTWIN.CPP THSTVIEW.CPP TINDICTR.CPP TINPUTLI.CPP TLABEL.CPP TLISTBOX.CPP TLSTVIEW.CPP TMEMO.CPP TMENUBAR.CPP TMENUBOX.CPP TMNUVIEW.CPP TMOUSE.CPP TOBJECT.CPP TOBJSTRM.CPP TPARAMTE.CPP TPOINT.CPP TPROGRAM.CPP TRADIOBU.CPP TRESCOLL.CPP TRESFILE.CPP TSCREEN.CPP TSCRLBAR.CPP TSCROLLE.CPP TSORTCOL.CPP TSTATICT.CPP TSTATUSL.CPP TSTRCOLL.CPP TSTRLIST.CPP TTPRVLNS.ASM TVCURSOR.ASM TVEXPOSD.ASM TVIEW.CPP TVLIB.RSP TVTEXT1.CPP TVTEXT2.CPP TVWRITE.ASM TVWRITE.INC TWINDOW.CPP

ARCHIVE_BCP20AF_WBIN:=BC.ICO HC.EXE IMPDEF.EXE IMPL2MSG.EXE IMPLIB.EXE RC.EXE RC2MSG.EXE RCPP.ERR RCPP.EXE WINSTUB.EXE WRT.DAT WRT.EXE WRT.FON WRT.HLP WRT.IMA
BCP20AF_TARGETS:=$(BCP20AF_TARGETS) $(patsubst %,$(DSTDIR_BCP20AF)BIN/%,$(ARCHIVE_BCP20AF_WBIN))
$(patsubst %,$(DSTDIR_BCP20AF)BIN/%,$(ARCHIVE_BCP20AF_WBIN)) &: osdisks/bcp20axx/WBIN.ZIP
	install -D -d $(DSTDIR_BCP20AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP20AF)BIN/ $<

ARCHIVE_BCP20AF_WEXAMPLE:=BITMAP.CPP BITMAP.DEF BITMAP.DLL BITMAP.H BITMAP.PRJ BITMAP.RC BULLET.BMP CHKBOFF.BMP CHKBON.BMP CODEC.BMP CONTINUE.BMP DDECLNT.C DDECLNT.H DDESRVR.C DDESRVR.H DLLDEMO.CPP DLLDEMO.DEF DLLDEMO.ICO DLLDEMO.PRJ DLLDEMO.RC DLLDEMO1.BMP DLLDEMO2.BMP DLLSHELL.CPP DONE.BMP FFIND.C FFIND.DEF FFIND.H FFIND.ICO FFIND.PRJ FFIND.RC HDUMP.C HDUMP.DEF HDUMP.H HDUMP.ICO HDUMP.PRJ HDUMP.RC HELP.CUR HELPEX.C HELPEX.DEF HELPEX.DLG HELPEX.H HELPEX.HLP HELPEX.HPJ HELPEX.PH HELPEX.PRJ HELPEX.RC HELPEX.RTF HELPICON.BMP HELPIDS.H KEYS.RTF MAX2ICON.BMP MOUSE.BMP MSGPROC.C MSGPROC.H MSGWND.C MSGWND.DEF MSGWND.H MSGWND.ICO MSGWND.PRJ MSGWND.RC TERMS.RTF TODO.DEF TODO.PRJ TODODEFS.H TODODLGS.CPP TODODLGS.H TODOLIST.CPP TODOLIST.H TODOWIN.CPP TODOWIN.H TODOWIN.RC TSTAPP.C TSTAPP.DEF TSTAPP.H TSTAPP.ICO TSTAPP.PRJ TSTAPP.RC WHELLO.CPP WHELLO.DEF WHELLO.ICO WHELLO.MAK WHELLO.PRJ WHELLO.RC WINWORD.BMP
ARCHIVE_BCP20AF_WHELP:=TCHELPW.TCH

ARCHIVE_BCP20AF_WINCLUDE:=CUSTCNTL.H DDE.H DRIVINIT.H WINDOWS.H WINDOWS.INC
BCP20AF_TARGETS:=$(BCP20AF_TARGETS) $(patsubst %,$(DSTDIR_BCP20AF)INCLUDE/%,$(ARCHIVE_BCP20AF_WINCLUDE))
$(patsubst %,$(DSTDIR_BCP20AF)INCLUDE/%,$(ARCHIVE_BCP20AF_WINCLUDE)) &: osdisks/bcp20axx/WINCLUDE.ZIP
	install -D -d $(DSTDIR_BCP20AF)INCLUDE/
	unzip -DD -o -d $(DSTDIR_BCP20AF)INCLUDE/ $<

ARCHIVE_BCP20AF_WINLIB:=C0WC.OBJ C0WL.OBJ C0WM.OBJ C0WS.OBJ CWINC.LIB CWINL.LIB CWINM.LIB CWINS.LIB
BCP20AF_TARGETS:=$(BCP20AF_TARGETS) $(patsubst %,$(DSTDIR_BCP20AF)LIB/%,$(ARCHIVE_BCP20AF_WINLIB))
$(patsubst %,$(DSTDIR_BCP20AF)LIB/%,$(ARCHIVE_BCP20AF_WINLIB)) &: osdisks/bcp20axx/WINLIB.ZIP
	install -D -d $(DSTDIR_BCP20AF)LIB/
	unzip -DD -o -d $(DSTDIR_BCP20AF)LIB/ $<

ARCHIVE_BCP20AF_WLOBJ:=VERSION.OBJ
ARCHIVE_BCP20AF_WMOBJ:=VERSION.OBJ
ARCHIVE_BCP20AF_WSOBJ:=VERSION.OBJ

ARCHIVE_BCP20AF_XLIB:=EMU.LIB FP87.LIB GRAPHICS.LIB IMPORT.LIB MATHERR.C OVERLAY.LIB WILDARGS.OBJ
BCP20AF_TARGETS:=$(BCP20AF_TARGETS) $(patsubst %,$(DSTDIR_BCP20AF)LIB/%,$(ARCHIVE_BCP20AF_XLIB))
$(patsubst %,$(DSTDIR_BCP20AF)LIB/%,$(ARCHIVE_BCP20AF_XLIB)) &: osdisks/bcp20axx/XLIB.ZIP
	install -D -d $(DSTDIR_BCP20AF)LIB/
	unzip -DD -o -d $(DSTDIR_BCP20AF)LIB/ $<

# TEST --GM
BCP20AF_TARGETS:=$(BCP20AF_TARGETS) $(MERGE_BCP20AF_ARCHIVES)

.PHONY: prepare-bcp20af
prepare-bcp20af: $(BCP20AF_TARGETS)

