#
# Borland C++ 3.0 with Application Frameworks, 5.25" 1200K version
#

# FIXME: Missing BIN/THELP.CFG
# FIXME: Missing BIN/TLINK.CFG
# FIXME: Missing BIN/TURBOC.CFG
# FIXME: Missing OWL/EXAMPLES/BCROOT.INC
# FIXME: Missing TVISION/OBJECT/

# NOTE: *SHOULD* be C:\BORLANDC, as BC.EXE + TCW.EXE gets modified by the installer if it isn't.
DSTDIR_BCP30AF:=target/root/BORLANDC/

SRCDIR_BCP30AF_DISKS:=packages/bcp30af/
DISK_BCP30AF_01:=CALC.ZIP CLASSINC.ZIP DISK1.DSK DLOBJ.ZIP EXAMPLES.ZIP FILEAPP.ZIP FILELIST.DOC INCLUDE.ZIP INSTALL.EXE OWLSRC.ZIP README README.COM TD.CA2 TDW.CA2 TVINC.ZIP UNZIP.EXE WHELP2.CA4
DISK_BCP30AF_02:=BC.CA1 BIN.ZIP CLASSBLD.ZIP CURSOR.ZIP DISK2.DSK TVDEMOS.ZIP TVSRC.ZIP WHELP2.CA3 WLOBJ.ZIP
DISK_BCP30AF_03:=CLASSEXM.ZIP CMDLINE.CA1 DISK3.DSK OWLINC.ZIP WHELP2.CA2 WHEREIS.ZIP WINLIB.CA1 WMOBJ.ZIP
DISK_BCP30AF_04:=BGI.ZIP BINDLL.ZIP BONK.ZIP CHECKERS.ZIP DISK4.DSK GDIDEMO.ZIP MFILEAPP.ZIP OWLDEMOS.ZIP OWLDOC.ZIP PAINT.ZIP RWCDEMO.ZIP RWDOC.ZIP STARTUP.ZIP TASMEXMP.ZIP TDWEXMPL.ZIP WCOBJ.ZIP WEXAMPLE.ZIP WHELP1.CA5 WINCLUDE.ZIP WSOBJ.ZIP
DISK_BCP30AF_05:=BINSRC.ZIP BWCC.ZIP CLIB.ZIP DISK5.DSK HEAP.ZIP LLIB.ZIP MLIB.ZIP OWL.ZIP PROGTALK.ZIP QUEUE.ZIP SYSINFO.ZIP TTT.ZIP WHELP1.CA3 WHELP1.CA4
DISK_BCP30AF_06:=DISK6.DSK DOC.ZIP FILT.ZIP HLIB.ZIP SLIB.ZIP STEPS.ZIP TASM.CA1 WHELP1.CA2
DISK_BCP30AF_07:=BATSRC.ZIP DISK7.DSK EMUSRC.ZIP IDE.ZIP OWLLIB.CA2 RW.CA1 RW.CA2 TASM.CA2 TCALC.ZIP TFEXMPL.ZIP XLIB.ZIP
DISK_BCP30AF_08:=DISK8.DSK INDEPSRC.ZIP OWLLIB.CA1 TDEXMPL.ZIP TVDOCDEM.ZIP WHELP1.CA1 WHELP2.CA1
DISK_BCP30AF_09:=DISK9.DSK RTLINSRC.ZIP TD.CA1 TDW.CA1 TVHELP.ZIP WBIN.CA2
DISK_BCP30AF_10:=BC.CA2 CLIBSRC.ZIP CLIBSRC1.ZIP DISK10.DSK TPROFW.ZIP WBIN.CA1 WINLIB.CA2
DISK_BCP30AF_11:=CLIBSRC2.ZIP DISK11.DSK IOSTRSR1.ZIP IOSTRSRC.ZIP MATHSRC.ZIP TDUTIL.ZIP TPROF.ZIP TVLIB.ZIP WINLBSRC.ZIP
DISK_BCP30AF_12:=CLASSLIB.ZIP CLASSSRC.ZIP CLIBSRC3.ZIP CMDLINE.CA2 DISK12.DSK RW.CA3 WBIN.CA3

EXTRACT_BCP30AF_DISKS:=\
	$(patsubst %,osdisks/bcp30a01/%,$(DISK_BCP30AF_01)) \
	$(patsubst %,osdisks/bcp30a02/%,$(DISK_BCP30AF_02)) \
	$(patsubst %,osdisks/bcp30a03/%,$(DISK_BCP30AF_03)) \
	$(patsubst %,osdisks/bcp30a04/%,$(DISK_BCP30AF_04)) \
	$(patsubst %,osdisks/bcp30a05/%,$(DISK_BCP30AF_05)) \
	$(patsubst %,osdisks/bcp30a06/%,$(DISK_BCP30AF_06)) \
	$(patsubst %,osdisks/bcp30a07/%,$(DISK_BCP30AF_07)) \
	$(patsubst %,osdisks/bcp30a08/%,$(DISK_BCP30AF_08)) \
	$(patsubst %,osdisks/bcp30a09/%,$(DISK_BCP30AF_09)) \
	$(patsubst %,osdisks/bcp30a10/%,$(DISK_BCP30AF_10)) \
	$(patsubst %,osdisks/bcp30a11/%,$(DISK_BCP30AF_11)) \
	$(patsubst %,osdisks/bcp30a12/%,$(DISK_BCP30AF_12)) \
	#
MERGE_BCP30AF_DISKS:=\
	$(sort \
		$(patsubst %,osdisks/bcp30axx/%,$(DISK_BCP30AF_01)) \
		$(patsubst %,osdisks/bcp30axx/%,$(DISK_BCP30AF_02)) \
		$(patsubst %,osdisks/bcp30axx/%,$(DISK_BCP30AF_03)) \
		$(patsubst %,osdisks/bcp30axx/%,$(DISK_BCP30AF_04)) \
		$(patsubst %,osdisks/bcp30axx/%,$(DISK_BCP30AF_05)) \
		$(patsubst %,osdisks/bcp30axx/%,$(DISK_BCP30AF_06)) \
		$(patsubst %,osdisks/bcp30axx/%,$(DISK_BCP30AF_07)) \
		$(patsubst %,osdisks/bcp30axx/%,$(DISK_BCP30AF_08)) \
		$(patsubst %,osdisks/bcp30axx/%,$(DISK_BCP30AF_09)) \
		$(patsubst %,osdisks/bcp30axx/%,$(DISK_BCP30AF_10)) \
		$(patsubst %,osdisks/bcp30axx/%,$(DISK_BCP30AF_11)) \
		$(patsubst %,osdisks/bcp30axx/%,$(DISK_BCP30AF_12)) \
	)

$(patsubst %,osdisks/bcp30a01/%,$(DISK_BCP30AF_01)) &: $(SRCDIR_BCP30AF_DISKS)disk01.img
	(install -D -d osdisks/bcpBIN/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp30a01/)
$(patsubst %,osdisks/bcp30a02/%,$(DISK_BCP30AF_02)) &: $(SRCDIR_BCP30AF_DISKS)disk02.img
	(install -D -d osdisks/bcp30a02/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp30a02/)
$(patsubst %,osdisks/bcp30a03/%,$(DISK_BCP30AF_03)) &: $(SRCDIR_BCP30AF_DISKS)disk03.img
	(install -D -d osdisks/bcp30a03/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp30a03/)
$(patsubst %,osdisks/bcp30a04/%,$(DISK_BCP30AF_04)) &: $(SRCDIR_BCP30AF_DISKS)disk04.img
	(install -D -d osdisks/bcp30a04/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp30a04/)
$(patsubst %,osdisks/bcp30a05/%,$(DISK_BCP30AF_05)) &: $(SRCDIR_BCP30AF_DISKS)disk05.img
	(install -D -d osdisks/bcp30a05/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp30a05/)
$(patsubst %,osdisks/bcp30a06/%,$(DISK_BCP30AF_06)) &: $(SRCDIR_BCP30AF_DISKS)disk06.img
	(install -D -d osdisks/bcp30a06/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp30a06/)
$(patsubst %,osdisks/bcp30a07/%,$(DISK_BCP30AF_07)) &: $(SRCDIR_BCP30AF_DISKS)disk07.img
	(install -D -d osdisks/bcp30a07/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp30a07/)
$(patsubst %,osdisks/bcp30a08/%,$(DISK_BCP30AF_08)) &: $(SRCDIR_BCP30AF_DISKS)disk08.img
	(install -D -d osdisks/bcp30a08/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp30a08/)
$(patsubst %,osdisks/bcp30a09/%,$(DISK_BCP30AF_09)) &: $(SRCDIR_BCP30AF_DISKS)disk09.img
	(install -D -d osdisks/bcp30a09/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp30a09/)
$(patsubst %,osdisks/bcp30a10/%,$(DISK_BCP30AF_10)) &: $(SRCDIR_BCP30AF_DISKS)disk10.img
	(install -D -d osdisks/bcp30a10/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp30a10/)
$(patsubst %,osdisks/bcp30a11/%,$(DISK_BCP30AF_11)) &: $(SRCDIR_BCP30AF_DISKS)disk11.img
	(install -D -d osdisks/bcp30a11/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp30a11/)
$(patsubst %,osdisks/bcp30a12/%,$(DISK_BCP30AF_12)) &: $(SRCDIR_BCP30AF_DISKS)disk12.img
	(install -D -d osdisks/bcp30a12/ && mcopy -n -D o -s -i "$<" :: osdisks/bcp30a12/)

$(MERGE_BCP30AF_DISKS) &: $(EXTRACT_BCP30AF_DISKS)
	install -D -d osdisks/bcp30axx/
	cp -r osdisks/bcp30a01/* osdisks/bcp30axx/
	cp -r osdisks/bcp30a02/* osdisks/bcp30axx/
	cp -r osdisks/bcp30a03/* osdisks/bcp30axx/
	cp -r osdisks/bcp30a04/* osdisks/bcp30axx/
	cp -r osdisks/bcp30a05/* osdisks/bcp30axx/
	cp -r osdisks/bcp30a06/* osdisks/bcp30axx/
	cp -r osdisks/bcp30a07/* osdisks/bcp30axx/
	cp -r osdisks/bcp30a08/* osdisks/bcp30axx/
	cp -r osdisks/bcp30a09/* osdisks/bcp30axx/
	cp -r osdisks/bcp30a10/* osdisks/bcp30axx/
	cp -r osdisks/bcp30a11/* osdisks/bcp30axx/
	cp -r osdisks/bcp30a12/* osdisks/bcp30axx/

# Archive merging
BCP30AF_SPLIT_ARCHIVES:=BC.ZIP CMDLINE.ZIP WINLIB.ZIP TASM.ZIP RW.ZIP OWLLIB.ZIP WHELP1.ZIP WHELP2.ZIP TD.ZIP TDW.ZIP WBIN.ZIP
MERGE_BCP30AF_ARCHIVES:=$(patsubst %,osdisks/bcp30axx/%,$(BCP30AF_SPLIT_ARCHIVES))
osdisks/bcp30axx/BC.ZIP: osdisks/bcp30a02/BC.CA1 osdisks/bcp30a10/BC.CA2
	install -D -d osdisks/bcp30axx/
	(scripts/bccacat.sh $^ > $@.tmp) || (rm $@.tmp && false)
	mv $@.tmp $@
osdisks/bcp30axx/CMDLINE.ZIP: osdisks/bcp30a03/CMDLINE.CA1 osdisks/bcp30a12/CMDLINE.CA2
	install -D -d osdisks/bcp30axx/
	(scripts/bccacat.sh $^ > $@.tmp) || (rm $@.tmp && false)
	mv $@.tmp $@
osdisks/bcp30axx/WINLIB.ZIP: osdisks/bcp30a03/WINLIB.CA1 osdisks/bcp30a10/WINLIB.CA2
	install -D -d osdisks/bcp30axx/
	(scripts/bccacat.sh $^ > $@.tmp) || (rm $@.tmp && false)
	mv $@.tmp $@
osdisks/bcp30axx/TASM.ZIP: osdisks/bcp30a06/TASM.CA1 osdisks/bcp30a07/TASM.CA2
	install -D -d osdisks/bcp30axx/
	(scripts/bccacat.sh $^ > $@.tmp) || (rm $@.tmp && false)
	mv $@.tmp $@
osdisks/bcp30axx/RW.ZIP: osdisks/bcp30a07/RW.CA1 osdisks/bcp30a07/RW.CA2 osdisks/bcp30a12/RW.CA3
	install -D -d osdisks/bcp30axx/
	(scripts/bccacat.sh $^ > $@.tmp) || (rm $@.tmp && false)
	mv $@.tmp $@
osdisks/bcp30axx/OWLLIB.ZIP: osdisks/bcp30a08/OWLLIB.CA1 osdisks/bcp30a07/OWLLIB.CA2
	install -D -d osdisks/bcp30axx/
	(scripts/bccacat.sh $^ > $@.tmp) || (rm $@.tmp && false)
	mv $@.tmp $@
osdisks/bcp30axx/WHELP1.ZIP: osdisks/bcp30a08/WHELP1.CA1 osdisks/bcp30a06/WHELP1.CA2 osdisks/bcp30a05/WHELP1.CA3 osdisks/bcp30a05/WHELP1.CA4 osdisks/bcp30a04/WHELP1.CA5
	install -D -d osdisks/bcp30axx/
	(scripts/bccacat.sh $^ > $@.tmp) || (rm $@.tmp && false)
	mv $@.tmp $@
osdisks/bcp30axx/WHELP2.ZIP: osdisks/bcp30a08/WHELP2.CA1 osdisks/bcp30a03/WHELP2.CA2 osdisks/bcp30a02/WHELP2.CA3 osdisks/bcp30a01/WHELP2.CA4
	install -D -d osdisks/bcp30axx/
	(scripts/bccacat.sh $^ > $@.tmp) || (rm $@.tmp && false)
	mv $@.tmp $@
osdisks/bcp30axx/TD.ZIP: osdisks/bcp30a09/TD.CA1 osdisks/bcp30a01/TD.CA2
	install -D -d osdisks/bcp30axx/
	(scripts/bccacat.sh $^ > $@.tmp) || (rm $@.tmp && false)
	mv $@.tmp $@
osdisks/bcp30axx/TDW.ZIP: osdisks/bcp30a09/TDW.CA1 osdisks/bcp30a01/TDW.CA2
	install -D -d osdisks/bcp30axx/
	(scripts/bccacat.sh $^ > $@.tmp) || (rm $@.tmp && false)
	mv $@.tmp $@
osdisks/bcp30axx/WBIN.ZIP: osdisks/bcp30a10/WBIN.CA1 osdisks/bcp30a09/WBIN.CA2 osdisks/bcp30a12/WBIN.CA3
	install -D -d osdisks/bcp30axx/
	(scripts/bccacat.sh $^ > $@.tmp) || (rm $@.tmp && false)
	mv $@.tmp $@

# Actually extracting files

# for A in $(echo $(echo -n osdisks/bcp30axx/*.ZIP) | sort); do echo "ARCHIVE_BCP30AF_$(echo -n $A | sed -e 's#\.ZIP##g' -e 's#.*/##g'):=$(echo $(unzip -Z -1 $A 2>/dev/null))"; done
BCP30AF_ARCHIVE_NAMES:=BATSRC BC BGI BIN BINDLL BINSRC BONK BWCC CALC CHECKERS CLASSBLD CLASSEXM CLASSINC CLASSLIB CLASSSRC CLIB CLIBSRC CLIBSRC1 CLIBSRC2 CLIBSRC3 CMDLINE CURSOR DLOBJ DOC EMUSRC EXAMPLES FILEAPP FILT GDIDEMO HEAP HLIB IDE INCLUDE INDEPSRC IOSTRSR1 IOSTRSRC LLIB MATHSRC MFILEAPP MLIB OWL OWLDEMOS OWLDOC OWLINC OWLLIB OWLSRC PAINT PROGTALK QUEUE RTLINSRC RW RWCDEMO RWDOC SLIB STARTUP STEPS SYSINFO TASM TASMEXMP TCALC TD TDEXMPL TDUTIL TDW TDWEXMPL TFEXMPL TPROF TPROFW TTT TVDEMOS TVDOCDEM TVHELP TVINC TVLIB TVSRC WBIN WCOBJ WEXAMPLE WHELP1 WHELP2 WHEREIS WINCLUDE WINLBSRC WINLIB WLOBJ WMOBJ WSOBJ XLIB
BCP30AF_ARCHIVE_FILES:=$(patsubst %,osdisks/bcp30axx/%.ZIP,$(BCP30AF_ARCHIVE_NAMES))

# Initial empty list
BCP30AF_TARGETS:=

ARCHIVE_BCP30AF_BATSRC:=ALL.BAT BUILD.BAT CRTL.DOC MAKEDIRS.BAT MAKEFILE RETURN.TXT RULES.MAK VARS.BAT
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)CRTL/%,$(ARCHIVE_BCP30AF_BATSRC))
$(patsubst %,$(DSTDIR_BCP30AF)CRTL/%,$(ARCHIVE_BCP30AF_BATSRC)) &: osdisks/bcp30axx/BATSRC.ZIP
	install -D -d $(DSTDIR_BCP30AF)CRTL/
	unzip -DD -o -d $(DSTDIR_BCP30AF)CRTL/ $<

ARCHIVE_BCP30AF_BC:=BC.EXE
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_BC))
$(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_BC)) &: osdisks/bcp30axx/BC.ZIP
	install -D -d $(DSTDIR_BCP30AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP30AF)BIN/ $<

ARCHIVE_BCP30AF_BGI:=ATT.BGI BGIDEMO.C BGIOBJ.EXE BOLD.CHR CGA.BGI EGAVGA.BGI EURO.CHR GOTH.CHR HERC.BGI IBM8514.BGI LCOM.CHR LITT.CHR PC3270.BGI SANS.CHR SCRI.CHR SIMP.CHR TRIP.CHR TSCR.CHR
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)BGI/%,$(ARCHIVE_BCP30AF_BGI))
$(patsubst %,$(DSTDIR_BCP30AF)BGI/%,$(ARCHIVE_BCP30AF_BGI)) &: osdisks/bcp30axx/BGI.ZIP
	install -D -d $(DSTDIR_BCP30AF)BGI/
	unzip -DD -o -d $(DSTDIR_BCP30AF)BGI/ $<

ARCHIVE_BCP30AF_BIN:=DPMI16BI.OVL DPMIINST.EXE DPMILOAD.EXE DPMIMEM.DLL DPMIRES.EXE EMSTEST.COM GREP.COM IMPDEF.EXE IMPLIB.EXE OBJXREF.COM PRJ2MAK.EXE PRJCFG.EXE TLIB.EXE TOUCH.COM TRANCOPY.EXE TRIGRAPH.EXE
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_BIN))
$(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_BIN)) &: osdisks/bcp30axx/BIN.ZIP
	install -D -d $(DSTDIR_BCP30AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP30AF)BIN/ $<

ARCHIVE_BCP30AF_BINDLL:=BC30RTL.DLL BIDS.DLL OWL.DLL TCLASS.DLL
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_BINDLL))
$(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_BINDLL)) &: osdisks/bcp30axx/BINDLL.ZIP
	install -D -d $(DSTDIR_BCP30AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP30AF)BIN/ $<

ARCHIVE_BCP30AF_BINSRC:=MAKERSP.EXE
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_BINSRC))
$(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_BINSRC)) &: osdisks/bcp30axx/BINSRC.ZIP
	install -D -d $(DSTDIR_BCP30AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP30AF)BIN/ $<

ARCHIVE_BCP30AF_BONK:=BOARD.BMP BOARD2.BMP BONK.CPP BONK.H BONK.PRJ BONK.RC BONK.RES BONK2.RC BONK2.RES CRITTER.ICO CRITTER2.ICO DEAD.BMP DEAD2.BMP GAMEOVE2.BMP GAMEOVER.BMP LIVE.BMP LIVE2.BMP MAKEFILE MALET.CUR MALET2.CUR MALETDO2.CUR MALETDOW.CUR
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/BONK/%,$(ARCHIVE_BCP30AF_BONK))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/BONK/%,$(ARCHIVE_BCP30AF_BONK)) &: osdisks/bcp30axx/BONK.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/BONK/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/BONK/ $<

ARCHIVE_BCP30AF_BWCC:=BWCC.DLL
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_BWCC))
$(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_BWCC)) &: osdisks/bcp30axx/BWCC.ZIP
	install -D -d $(DSTDIR_BCP30AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP30AF)BIN/ $<

ARCHIVE_BCP30AF_CALC:=CALC.CPP CALC.ICO CALC.PRJ CALC.RC CALC.RES MAKEFILE
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/CALC/%,$(ARCHIVE_BCP30AF_CALC))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/CALC/%,$(ARCHIVE_BCP30AF_CALC)) &: osdisks/bcp30axx/CALC.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/CALC/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/CALC/ $<

ARCHIVE_BCP30AF_CHECKERS:=BLACKKNG.BMP BLACKMAN.BMP BOARD.CPP BOARD.H CHECKERS.CPP CHECKERS.H CHECKERS.ICO CHECKERS.PRJ CHECKERS.RC CHECKERS.RES HAND.CUR HANDPC.CUR INFO.CPP INFO.H MAKEFILE REDKING.BMP REDMAN.BMP
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/CHECKERS/%,$(ARCHIVE_BCP30AF_CHECKERS))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/CHECKERS/%,$(ARCHIVE_BCP30AF_CHECKERS)) &: osdisks/bcp30axx/CHECKERS.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/CHECKERS/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/CHECKERS/ $<

ARCHIVE_BCP30AF_CLASSBLD:=MAKEFILE
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)CLASSLIB/%,$(ARCHIVE_BCP30AF_CLASSBLD))
$(patsubst %,$(DSTDIR_BCP30AF)CLASSLIB/%,$(ARCHIVE_BCP30AF_CLASSBLD)) &: osdisks/bcp30axx/CLASSBLD.ZIP
	install -D -d $(DSTDIR_BCP30AF)CLASSLIB/
	unzip -DD -o -d $(DSTDIR_BCP30AF)CLASSLIB/ $<

ARCHIVE_BCP30AF_CLASSEXM:=DIRECTRY.CPP DIRECTRY.H DIRECTRY.PRJ FILEDATA.CPP FILEDATA.H LOOKUP.CPP LOOKUP.PRJ QUEUETST.CPP QUEUETST.PRJ REVERSE.CPP REVERSE.PRJ STRNGMAX.CPP STRNGMAX.PRJ TESTDIR.CPP
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)CLASSLIB/EXAMPLES/%,$(ARCHIVE_BCP30AF_CLASSEXM))
$(patsubst %,$(DSTDIR_BCP30AF)CLASSLIB/EXAMPLES/%,$(ARCHIVE_BCP30AF_CLASSEXM)) &: osdisks/bcp30axx/CLASSEXM.ZIP
	install -D -d $(DSTDIR_BCP30AF)CLASSLIB/EXAMPLES/
	unzip -DD -o -d $(DSTDIR_BCP30AF)CLASSLIB/EXAMPLES/ $<

ARCHIVE_BCP30AF_CLASSINC:=ABSTARRY.H ARRAY.H ARRAYS.H ASSOC.H BAG.H BAGS.H BTREE.H CHECKS.H CLSDEFS.H CLSTYPES.H COLLECT.H CONTAIN.H DBLLIST.H DEQUE.H DEQUES.H DICT.H DLISTIMP.H HASHTBL.H LDATE.H LIST.H LISTIMP.H LTIME.H MEMMGR.H OBJECT.H PRIORTYQ.H QUEUE.H QUEUES.H RESOURCE.H SET.H SETS.H SHDDEL.H SORTABLE.H SORTARRY.H STACK.H STACKS.H STDTEMPL.H STRNG.H TIMER.H VECTIMP.H
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)CLASSLIB/INCLUDE/%,$(ARCHIVE_BCP30AF_CLASSINC))
$(patsubst %,$(DSTDIR_BCP30AF)CLASSLIB/INCLUDE/%,$(ARCHIVE_BCP30AF_CLASSINC)) &: osdisks/bcp30axx/CLASSINC.ZIP
	install -D -d $(DSTDIR_BCP30AF)CLASSLIB/INCLUDE/
	unzip -DD -o -d $(DSTDIR_BCP30AF)CLASSLIB/INCLUDE/ $<

ARCHIVE_BCP30AF_CLASSLIB:=BIDSDBS.LIB BIDSDLL.LIB BIDSS.LIB TCLASDBS.LIB TCLASDLL.LIB TCLASSS.LIB
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)CLASSLIB/LIB/%,$(ARCHIVE_BCP30AF_CLASSLIB))
$(patsubst %,$(DSTDIR_BCP30AF)CLASSLIB/LIB/%,$(ARCHIVE_BCP30AF_CLASSLIB)) &: osdisks/bcp30axx/CLASSLIB.ZIP
	install -D -d $(DSTDIR_BCP30AF)CLASSLIB/LIB/
	unzip -DD -o -d $(DSTDIR_BCP30AF)CLASSLIB/LIB/ $<

ARCHIVE_BCP30AF_CLASSSRC:=ABSTARRY.CPP ARRAY.CPP ASSOC.CPP BABSTARY.CPP BDICT.CPP BIDS.DEF BSORTARY.CPP BTREE.CPP BTREEINN.CPP BTREELFN.CPP CLASMAIN.CPP COLLECT.CPP CONTAIN.CPP DBLLIST.CPP DEQUE.CPP DICT.CPP HASHTBL.CPP LDATE.CPP LIST.CPP LTIME.CPP MEMMGR.CPP OBJECT.CPP SORTARRY.CPP STACK.CPP STRNG.CPP TCLASS.DEF TIMER.CPP TMPLINST.CPP
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)CLASSLIB/SOURCE/%,$(ARCHIVE_BCP30AF_CLASSSRC))
$(patsubst %,$(DSTDIR_BCP30AF)CLASSLIB/SOURCE/%,$(ARCHIVE_BCP30AF_CLASSSRC)) &: osdisks/bcp30axx/CLASSSRC.ZIP
	install -D -d $(DSTDIR_BCP30AF)CLASSLIB/SOURCE/
	unzip -DD -o -d $(DSTDIR_BCP30AF)CLASSLIB/SOURCE/ $<

ARCHIVE_BCP30AF_CLIB:=C0C.OBJ C0DC.OBJ C0FC.OBJ CC.LIB MATHC.LIB
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)LIB/%,$(ARCHIVE_BCP30AF_CLIB))
$(patsubst %,$(DSTDIR_BCP30AF)LIB/%,$(ARCHIVE_BCP30AF_CLIB)) &: osdisks/bcp30axx/CLIB.ZIP
	install -D -d $(DSTDIR_BCP30AF)LIB/
	unzip -DD -o -d $(DSTDIR_BCP30AF)LIB/ $<

ARCHIVE_BCP30AF_CLIBSRC:=ABS.CAS ASSERT.C BCD2.CPP BDOS.CAS BIOSCOM.CAS BIOSPRIN.CAS CHDIR.CAS CLEARERR.C CLIB.MAK CLIBOBJ.MAK CLREOL.C CLRSCR.C CONSTREA.CPP CPUTS.C CURSOR.C DEL.CPP DELF.CPP ERRORMSG.C EXECLPE.C EXECVE.C FARFUNCS.MAK FDDVT.ASM FDOPEN.C FFMALLOC.C FGETPOS.C FILES2.C FMODE.C FPRINTF.C FPSTKLEN.C FREEMEM.CAS FREOPEN.C FSETPOS.C F_PCMP.ASM F_SCOPY.ASM GETPSP.C GETW.C GEXIT.C GFREEMEM.C GGETMEM.C GOTOXY.C HEAPLEN.C H_LLSH.ASM H_LRSH.ASM H_LURSH.ASM H_PSBH.ASM ISATTY.CAS KEEP.C LABS.C LOCALE.C LROTL.CAS LROTR.CAS NEW.CPP NEWF.CPP N_PCMP.ASM N_SCOPY.ASM PRINTF.C PUREERR.CPP PUTCH.C READU.ASM REALCVT.ASM REWIND.C ROTL.CAS ROTR.CAS SCANTOD.ASM SETDTA.CAS SETFTIME.CAS SETUPIO.C SIGDATA.C SRCHPATH.C STKLEN.C STRCOLL.C STRSET.C STRXFRM.C TASM.CFG TELL.C TMPNAM.C TURBOC.CFG VFPRINTF.C VFSCANF.C VNEWVF.CPP VNEWVN.CPP VPRINTF.C VSCANF.C WILD.ASM WILDARGS.ASM WRITEU.ASM WSCROLL.C XCLOSE.C XFCLOSE.C XFFLUSH.C
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)CRTL/CLIB/%,$(ARCHIVE_BCP30AF_CLIBSRC))
$(patsubst %,$(DSTDIR_BCP30AF)CRTL/CLIB/%,$(ARCHIVE_BCP30AF_CLIBSRC)) &: osdisks/bcp30axx/CLIBSRC.ZIP
	install -D -d $(DSTDIR_BCP30AF)CRTL/CLIB/
	unzip -DD -o -d $(DSTDIR_BCP30AF)CRTL/CLIB/ $<

ARCHIVE_BCP30AF_CLIBSRC1:=ACCESS.C ALLOCMEM.CAS ATEXIT.C BDOSPTR.CAS BIOSDISK.CAS BIOS_COM.CAS BIOS_DSK.CAS BIOS_PRN.CAS CALLOC.C CHDRIVE.C CHMOD.C CHMODA.CAS CLOSE.C CLOSEA.CAS CLOSEALL.C CORELEFT.CAS COUNTRY.CAS CSCANF.C DIVT.CAS DOSALLOC.C DOSCLOSE.C DOSDFREE.C DOSEXT.CAS DOSFREE.C DOSGDRIV.C DOSGFTIM.C DOSKEEP.C DOSREAD.CAS DOSSETBL.C DOSSFTIM.C DOSWRITE.CAS FCLOSE.C FCORELFT.C FFLUSH.C FGETS.C FILES.C FLENGTH.CAS FLUSHALL.C FPUTS.C FSCANF.C F_LXMUL.ASM GETCBRK.C GETCURDI.CAS GETDISK.C GETDTA.CAS GETS.C GETSWIT.C GREGISTR.C H_PADD.ASM H_PSBP.ASM H_SPUSH.ASM INSLINE.C KBHIT.CAS LOCK.CAS MEMCHR.CAS MEMCMP.CAS MEMCPY.CAS MEMICMP.C MEMSET.CAS MKDIR.CAS MOVEDATA.CAS MOVETEXT.C MULTBYTE.C N_LXMUL.ASM OPENA.CAS PEEK.C PUTS.C PUTW.C RAND.C REMOVE.CAS RENAME.CAS RMDIR.CAS RMTMP.C SCANF.C SEGREAD.CAS SETBLOCK.CAS SETDATE.CAS SETMODE.C SLEEP.C SOPEN.C SOUND.CAS STACK.ASM STIME.C STPCPY.C STRCPY.CAS STRCSPN.C STRDUP.C STRLEN.CAS STRLWR.CAS STRNCAT.C STRNSET.C STRPBRK.C STRRCHR.C STRSPN.C STRUPR.CAS SWAB.CAS TMPFILE.C TOLOWER.C TOUPPER.C UMASK.C UNLINK.CAS VIDINFO.C _FSOPEN.C _STPCPY.C
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)CRTL/CLIB/%,$(ARCHIVE_BCP30AF_CLIBSRC1))
$(patsubst %,$(DSTDIR_BCP30AF)CRTL/CLIB/%,$(ARCHIVE_BCP30AF_CLIBSRC1)) &: osdisks/bcp30axx/CLIBSRC1.ZIP
	install -D -d $(DSTDIR_BCP30AF)CRTL/CLIB/
	unzip -DD -o -d $(DSTDIR_BCP30AF)CRTL/CLIB/ $<

ARCHIVE_BCP30AF_CLIBSRC2:=BIOSEQU.CAS BIOSKEY.CAS BIOS_EQU.CAS BIOS_KEY.CAS BRK.CAS BSEARCH.C CASTMPTR.CPP CGETS.C CHAININT.ASM CHSIZE.CAS CLOCK.CAS CPLX1.CPP CPRINTF.C CREAT.CAS CTRLBRK.C CTYPE.C CVTFAK.ASM DDVT.ASM DELAY.CAS DOSCMD.C DOSCREAT.CAS DOSENV.C DOSFATTR.CAS DOSGDATE.C DOSLOCK.C DOSOPEN.CAS DOSSDATE.C DOSSEEK.C DOSVECT.CAS DUP2.CAS EOF.CAS FBRK.C FCALLOC.CAS FNMERGE.C FNSPLIT.C FREAD.C FTIME.C FWRITE.C GETCH.CAS GETCWD.C GETDATE.C GETDCWD.CAS GETENV.CAS GETFAT.CAS GETFTIME.CAS GETPASS.C GETVECT.CAS GETVERF.CAS GPTEXT.C H_PADA.ASM H_PINA.ASM INPORT.CAS INTR.CAS IS.CAS LOADPROG.C LSEEK.CAS LTOA1.C MAKEPATH.C MEMCCPY.CAS MKNAME.C MKTEMP.C MOVMEM.CAS OUTPORT.CAS PARSFNM.CAS PERROR.C POKE.C RANDBLK.CAS READA.CAS SCROLL.C SPRINTF.C SSCANF.C STKAVAIL.ASM STRCAT.CAS STRCHR.CAS STRCMP.CAS STRDATE.C STRERROR.C STRICMP.CAS STRNCMP.CAS STRNCPY.CAS STRREV.CAS STRSTR.CAS STRTOK.C SYSTEM.C TEMPNAM.C TEXTMODE.C TIMECVT.C UNGETC.CAS UTIME.C VAPP.CPP VAPPV.CPP VDEL.CPP VDELN.CPP VNEW.CPP VNEWV.CPP WHEREXY.C WINDOW.C WRITEA.CAS
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)CRTL/CLIB/%,$(ARCHIVE_BCP30AF_CLIBSRC2))
$(patsubst %,$(DSTDIR_BCP30AF)CRTL/CLIB/%,$(ARCHIVE_BCP30AF_CLIBSRC2)) &: osdisks/bcp30axx/CLIBSRC2.ZIP
	install -D -d $(DSTDIR_BCP30AF)CRTL/CLIB/
	unzip -DD -o -d $(DSTDIR_BCP30AF)CRTL/CLIB/ $<

ARCHIVE_BCP30AF_CLIBSRC3:=ABSREAD.CAS ALLOCA.ASM ATOL.CAS BCD1.C COLOR.C CPLX2.CPP CREATA.CAS CRTINIT.CAS CTIME.C DIRECT.C DOSFIND.CAS DOSTIMU.CAS EXEC.ASM EXECL.C EXECLE.C EXECLP.C EXECV.C EXECVP.C EXECVPE.C EXIT.C FARHEAP.ASM FHEAPCHK.ASM FINDFIRS.CAS FOPEN.C FSEEK.C FSTAT.CAS FULLPATH.C GETC.CAS HARD.C HARDERR.CAS H_LDIV.ASM INT86.CAS INTDOS.CAS IOCTL.CAS IOERROR.CAS LDIVT.CAS LOCKING.C LONGTOA.CAS LSEARCH.C NEARHEAP.ASM NHEAPCHK.ASM OPEN.CAS PUTC.C PUTENV.CAS QSORT.CAS READ.CAS SCANNER.CAS SCANTOL.CAS SCREEN.C SEARCHP.CAS SETARGV.ASM SETBUF.C SETENVP.ASM SETJMP.CAS SETVBUF.C SIGNAL.C SPAWN.ASM SPAWNL.C SPAWNLE.C SPAWNLP.C SPAWNLPE.C SPAWNV.C SPAWNVE.C SPAWNVP.C SPAWNVPE.C SPLITPTH.C STAT.CAS STRNICMP.CAS STRTOL.C STRTOUL.C TZSET.CAS VDELF.CPP VNEWF.CPP VNEWN.CPP VPRINTER.CAS VRAM.CAS WRITE.C ZAPCTLZ.CAS
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)CRTL/CLIB/%,$(ARCHIVE_BCP30AF_CLIBSRC3))
$(patsubst %,$(DSTDIR_BCP30AF)CRTL/CLIB/%,$(ARCHIVE_BCP30AF_CLIBSRC3)) &: osdisks/bcp30axx/CLIBSRC3.ZIP
	install -D -d $(DSTDIR_BCP30AF)CRTL/CLIB/
	unzip -DD -o -d $(DSTDIR_BCP30AF)CRTL/CLIB/ $<

ARCHIVE_BCP30AF_CMDLINE:=BCC.EXE BUILTINS.MAK CPP.EXE MAKE.EXE MAKER.EXE TLINK.EXE
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_CMDLINE))
$(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_CMDLINE)) &: osdisks/bcp30axx/CMDLINE.ZIP
	install -D -d $(DSTDIR_BCP30AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP30AF)BIN/ $<

ARCHIVE_BCP30AF_CURSOR:=CURSOR.CPP CURSOR.DEF CURSOR.H CURSOR.ICO CURSOR.PRJ CURSOR.RC CURSOR.RES MAKEFILE
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/CURSOR/%,$(ARCHIVE_BCP30AF_CURSOR))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/CURSOR/%,$(ARCHIVE_BCP30AF_CURSOR)) &: osdisks/bcp30axx/CURSOR.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/CURSOR/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/CURSOR/ $<

ARCHIVE_BCP30AF_DLOBJ:=VERSION.OBJ
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/OBJECT/DL/%,$(ARCHIVE_BCP30AF_DLOBJ))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/OBJECT/DL/%,$(ARCHIVE_BCP30AF_DLOBJ)) &: osdisks/bcp30axx/DLOBJ.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/OBJECT/DL/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/OBJECT/DL/ $<

ARCHIVE_BCP30AF_DOC:=BRIEF.TEM CMACROS.TEM DBGBOARD.TD DEFAULTS.TEM DOSEDIT.TEM EPSILON.TEM H2ASH.TSM HDWDEBUG.TD HELPME!.DOC HELPME!.PRF HELPME!.TD HELPME!.TSM TCREF.TSM UTIL.DOC UTILS.PRF UTILS.TD WINMEM.DOC
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)DOC/%,$(ARCHIVE_BCP30AF_DOC))
$(patsubst %,$(DSTDIR_BCP30AF)DOC/%,$(ARCHIVE_BCP30AF_DOC)) &: osdisks/bcp30axx/DOC.ZIP
	install -D -d $(DSTDIR_BCP30AF)DOC/
	unzip -DD -o -d $(DSTDIR_BCP30AF)DOC/ $<

ARCHIVE_BCP30AF_EMUSRC:=E87TRANS.ASM EMURULES.ASI EMUVARS.ASI EQUATES.ASI FPINIT.ASM
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)CRTL/EMU/%,$(ARCHIVE_BCP30AF_EMUSRC))
$(patsubst %,$(DSTDIR_BCP30AF)CRTL/EMU/%,$(ARCHIVE_BCP30AF_EMUSRC)) &: osdisks/bcp30axx/EMUSRC.ZIP
	install -D -d $(DSTDIR_BCP30AF)CRTL/EMU/
	unzip -DD -o -d $(DSTDIR_BCP30AF)CRTL/EMU/ $<

ARCHIVE_BCP30AF_EXAMPLES:=BARCHART.C CPASDEMO.C CPASDEMO.PAS CTOPAS.CFG CTOPAS.PRJ DEF2.CPP DEF2.H FILTER.H GETOPT.C GREP2MSG.C HELLO.C IMPL2MSG.C LIST2.CPP LIST2.H MYFUNCS.CPP MYFUNCS.H MYMAIN.CPP MYPROG.DSK RC2MSG.C TASM2MSG.C VCIRC.CPP VCIRC.PRJ VPOINT.CPP VPOINT.H
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/%,$(ARCHIVE_BCP30AF_EXAMPLES))
$(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/%,$(ARCHIVE_BCP30AF_EXAMPLES)) &: osdisks/bcp30axx/EXAMPLES.ZIP
	install -D -d $(DSTDIR_BCP30AF)EXAMPLES/
	unzip -DD -o -d $(DSTDIR_BCP30AF)EXAMPLES/ $<

ARCHIVE_BCP30AF_FILEAPP:=FILEAPP.CPP FILEAPP.PRJ FILEAPP.RC FILEAPP.RES MAKEFILE
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/FILEAPP/%,$(ARCHIVE_BCP30AF_FILEAPP))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/FILEAPP/%,$(ARCHIVE_BCP30AF_FILEAPP)) &: osdisks/bcp30axx/FILEAPP.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/FILEAPP/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/FILEAPP/ $<

ARCHIVE_BCP30AF_FILT:=CONVERT1.INC CONVERT2.INC DEMO2.BAT DEMO3.BAT FILT.ASM FILT.DOC FILT.MAK FILT.RSP GLOBALS.INC OBYTEHI.ASM OBYTELOW.ASM OBYTENRM.ASM OCMDNUM.ASM OERREXIT.ASM OFCREATE.ASM OFILALOC.ASM OFILCLOS.ASM OFILEFIL.ASM OFILFREE.ASM OFILREAD.ASM OFILWRIT.ASM OFLFLUSH.ASM OFOPENR.ASM OFOPENW.ASM OLOCASE.ASM OPARSCMD.ASM OPRCBYTE.ASM OPROCDOC.ASM OPROCLIN.ASM OSETOPTN.ASM OSPACES.ASM OSTORSPC.ASM OSTORTAB.ASM OTABCLR.ASM OTABNEXT.ASM OTABRSET.ASM OTABSET.ASM OUPCASE.ASM SHOW87.ASM SHOW87.DOC VIDEO1.INC VIDEO2.INC
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/TASM/FILT/%,$(ARCHIVE_BCP30AF_FILT))
$(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/TASM/FILT/%,$(ARCHIVE_BCP30AF_FILT)) &: osdisks/bcp30axx/FILT.ZIP
	install -D -d $(DSTDIR_BCP30AF)EXAMPLES/TASM/FILT/
	unzip -DD -o -d $(DSTDIR_BCP30AF)EXAMPLES/TASM/FILT/ $<

ARCHIVE_BCP30AF_GDIDEMO:=ARTY.CPP ARTY.H ARTYPRIV.H BACKGRND.BMP BITBLT.CPP BITBLT.H DEMOBASE.H FONT.CPP FONT.H GDIDEMO.CPP GDIDEMO.PRJ GDIDEMO.RC GDIDEMO.RES LINE.CPP LINE.H MAKEFILE MONOSHIP.BMP SHIP.BMP
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/GDIDEMO/%,$(ARCHIVE_BCP30AF_GDIDEMO))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/GDIDEMO/%,$(ARCHIVE_BCP30AF_GDIDEMO)) &: osdisks/bcp30axx/GDIDEMO.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/GDIDEMO/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/GDIDEMO/ $<

ARCHIVE_BCP30AF_HEAP:=DEMO_MEM.BAT DISPLAY.ASM DISPLAY.INC MEM.ASM MEM.INC MEMTEST.ASM MEMTEST.MAK VMTUTIL.INC
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/TASM/HEAP/%,$(ARCHIVE_BCP30AF_HEAP))
$(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/TASM/HEAP/%,$(ARCHIVE_BCP30AF_HEAP)) &: osdisks/bcp30axx/HEAP.ZIP
	install -D -d $(DSTDIR_BCP30AF)EXAMPLES/TASM/HEAP/
	unzip -DD -o -d $(DSTDIR_BCP30AF)EXAMPLES/TASM/HEAP/ $<

ARCHIVE_BCP30AF_HLIB:=C0FH.OBJ C0H.OBJ CH.LIB MATHH.LIB
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)LIB/%,$(ARCHIVE_BCP30AF_HLIB))
$(patsubst %,$(DSTDIR_BCP30AF)LIB/%,$(ARCHIVE_BCP30AF_HLIB)) &: osdisks/bcp30axx/HLIB.ZIP
	install -D -d $(DSTDIR_BCP30AF)LIB/
	unzip -DD -o -d $(DSTDIR_BCP30AF)LIB/ $<

ARCHIVE_BCP30AF_IDE:=GREP2MSG.EXE IMPL2MSG.EXE PRJCNVT.EXE TASM2MSG.EXE TEMC.EXE
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_IDE))
$(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_IDE)) &: osdisks/bcp30axx/IDE.ZIP
	install -D -d $(DSTDIR_BCP30AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP30AF)BIN/ $<

ARCHIVE_BCP30AF_INCLUDE:=ALLOC.H ASSERT.H BCD.H BIOS.H COMPLEX.H CONIO.H CONSTREA.H CTYPE.H DIR.H DIRECT.H DIRENT.H DOS.H ERRNO.H FCNTL.H FLOAT.H FSTREAM.H GENERIC.H GRAPHICS.H IO.H IOMANIP.H IOSTREAM.H LIMITS.H LOCALE.H MALLOC.H MATH.H MEM.H MEMORY.H NEW.H PROCESS.H SEARCH.H SETJMP.H SHARE.H SIGNAL.H STDARG.H STDDEF.H STDIO.H STDIOSTR.H STDLIB.H STRING.H STRSTREA.H TIME.H UTIME.H VALUES.H VARARGS.H _DEFS.H _NULL.H
ARCHIVE_BCP30AF_INCLUDE_SYS:=LOCKING.H STAT.H TIMEB.H TYPES.H
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)INCLUDE/%,$(ARCHIVE_BCP30AF_INCLUDE)) $(patsubst %,$(DSTDIR_BCP30AF)INCLUDE/SYS/%,$(ARCHIVE_BCP30AF_INCLUDE_SYS))
$(patsubst %,$(DSTDIR_BCP30AF)INCLUDE/%,$(ARCHIVE_BCP30AF_INCLUDE)) &: osdisks/bcp30axx/INCLUDE.ZIP
	install -D -d $(DSTDIR_BCP30AF)INCLUDE/
	unzip -DD -o -d $(DSTDIR_BCP30AF)INCLUDE/ $< $(ARCHIVE_BCP30AF_INCLUDE)
$(patsubst %,$(DSTDIR_BCP30AF)INCLUDE/SYS/%,$(ARCHIVE_BCP30AF_INCLUDE_SYS)) &: osdisks/bcp30axx/INCLUDE.ZIP
	install -D -d $(DSTDIR_BCP30AF)INCLUDE/SYS/
	unzip -DD -o -d $(DSTDIR_BCP30AF)INCLUDE/SYS/ $< $(ARCHIVE_BCP30AF_INCLUDE_SYS)

ARCHIVE_BCP30AF_INDEPSRC:=NOTIMP.CPP NOTIMP.EXE NOTIMP.LST
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)CRTL/WINLIB/INDEP/%,$(ARCHIVE_BCP30AF_INDEPSRC))
$(patsubst %,$(DSTDIR_BCP30AF)CRTL/WINLIB/INDEP/%,$(ARCHIVE_BCP30AF_INDEPSRC)) &: osdisks/bcp30axx/INDEPSRC.ZIP
	install -D -d $(DSTDIR_BCP30AF)CRTL/WINLIB/INDEP/
	unzip -DD -o -d $(DSTDIR_BCP30AF)CRTL/WINLIB/INDEP/ $<

ARCHIVE_BCP30AF_IOSTRSR1:=FSATTCH.CPP FSBATTCH.CPP FSBCLOSE.CPP FSBCTR1.CPP FSBCTR2.CPP FSBCTR3.CPP FSBDTR.CPP FSBOFLOW.CPP FSBOPEN.CPP FSBSBUF.CPP FSBSKOFF.CPP FSBSYNC.CPP FSBUFLOW.CPP FSOPEN.CPP IOSRCTR2.CPP IOSTASN1.CPP IOSTASN2.CPP IOSTSTD.CPP ISTASN1.CPP ISTASN2.CPP ISTDGET.CPP ISTDIPFX.CPP ISTEATWH.CPP ISTEBUF.CPP ISTECHP.CPP ISTEDBL.CPP ISTEFLT.CPP ISTEINT.CPP ISTELDBL.CPP ISTELNG.CPP ISTESH.CPP ISTEUINT.CPP ISTEULNG.CPP ISTEUSH.CPP ISTGBUF.CPP ISTGET.CPP ISTGLINE.CPP ISTGSCHR.CPP ISTGSTR.CPP ISTGUCHR.CPP ISTIGN.CPP ISTPBACK.CPP ISTREAD.CPP ISTX.CPP MNRSTFLG.CPP MNSBASE.CPP MNSETFLG.CPP MNSETW.CPP MNSFILL.CPP MNSPREC.CPP OSRCTR1.CPP OSTASN1.CPP OSTASN2.CPP OSTFLOAT.CPP OSTIBUF.CPP OSTINT.CPP OSTISCHR.CPP OSTOPFX.CPP OSTOSFX.CPP OSTOUTST.CPP OSTPTR.CPP OSTSKOFF.CPP OSTTELLP.CPP OSTWRITE.CPP OSTX.CPP SDBCTR.CPP SDBOFLOW.CPP SDBSKOFF.CPP SDBSYNC.CPP SDBUFLOW.CPP SRBCTR3.CPP SRBCTR5.CPP SRBDALC.CPP SRBDTR.CPP SRBINIT.CPP SRBOFLOW.CPP SRBSBUF.CPP SRBSKOFF.CPP SRBSYNC.CPP SRBUFLOW.CPP STBCTR2.CPP STBDBP.CPP STBDSGTN.CPP STBDSPTN.CPP STBSETB.CPP STBSGETN.CPP STBSPUTN.CPP STBSTB1.CPP STBUFLOW.CPP STDTR.CPP STINIT.CPP STIWORD.CPP STPWORD.CPP STSETF1.CPP STSETF2.CPP STSKIP.CPP STSYNC.CPP STTIE.CPP STUSIZE.CPP
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)CRTL/IOSTREAM/%,$(ARCHIVE_BCP30AF_IOSTRSR1))
$(patsubst %,$(DSTDIR_BCP30AF)CRTL/IOSTREAM/%,$(ARCHIVE_BCP30AF_IOSTRSR1)) &: osdisks/bcp30axx/IOSTRSR1.ZIP
	install -D -d $(DSTDIR_BCP30AF)CRTL/IOSTREAM/
	unzip -DD -o -d $(DSTDIR_BCP30AF)CRTL/IOSTREAM/ $<

ARCHIVE_BCP30AF_IOSTRSRC:=FSCLOSE.CPP FSCTR1.CPP FSCTR2.CPP FSCTR3.CPP FSCTR4.CPP FSDTR.CPP FSSBUF.CPP IFSCTR1.CPP IFSCTR2.CPP IFSCTR3.CPP IFSCTR4.CPP IFSDTR.CPP IOFSCTR1.CPP IOFSCTR2.CPP IOFSCTR3.CPP IOFSCTR4.CPP IOFSDTR.CPP IOSRCTR1.CPP IOSRDTR.CPP IOSTCTR1.CPP IOSTCTR2.CPP IOSTCTR3.CPP IOSTDTR1.CPP IOSTDTR2.CPP IOSTOBJ.MAK IOSTREAM.MAK ISRCTR1.CPP ISRCTR2.CPP ISRDTR.CPP ISTCTR1.CPP ISTCTR2.CPP ISTCTR3.CPP ISTCTR4.CPP ISTDTR1.CPP ISTDTR2.CPP ISTESCHR.CPP ISTEUCHR.CPP ISTMANIP.CPP ISTSKOFF.CPP ISTSKPOS.CPP ISTTELLG.CPP ISTWS.CPP OFSCTR1.CPP OFSCTR2.CPP OFSCTR3.CPP OFSCTR4.CPP OFSDTR.CPP OSRCTR2.CPP OSRDTR.CPP OSTCTR1.CPP OSTCTR2.CPP OSTCTR3.CPP OSTDTR1.CPP OSTDTR2.CPP OSTENDL.CPP OSTENDS.CPP OSTFLUSH.CPP OSTMANIP.CPP OSTMFLSH.CPP OSTSKPOS.CPP SDBDTR.CPP SDBPBFL.CPP SDCTR.CPP SDDTR.CPP SRBCTR1.CPP SRBCTR2.CPP SRBCTR4.CPP SRBFREEZ.CPP SRBSTR.CPP SRCTR1.CPP SRCTR2.CPP SRDTR.CPP STBALC.CPP STBCTR1.CPP STBDNEXT.CPP STBDTR.CPP STBOFLOW.CPP STBPBFL.CPP STBSBUF.CPP STBSETG.CPP STBSETP.CPP STBSKOFF.CPP STBSKPOS.CPP STBSYNC.CPP STBTALC.CPP STCLEAR.CPP STCTR1.CPP STCTR2.CPP STDEC.CPP STFLAGS.CPP STHEX.CPP STOCT.CPP STSETST.CPP STUNSET.CPP STXALC.CPP TCDLL.CFG
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)CRTL/IOSTREAM/%,$(ARCHIVE_BCP30AF_IOSTRSRC))
$(patsubst %,$(DSTDIR_BCP30AF)CRTL/IOSTREAM/%,$(ARCHIVE_BCP30AF_IOSTRSRC)) &: osdisks/bcp30axx/IOSTRSRC.ZIP
	install -D -d $(DSTDIR_BCP30AF)CRTL/IOSTREAM/
	unzip -DD -o -d $(DSTDIR_BCP30AF)CRTL/IOSTREAM/ $<

ARCHIVE_BCP30AF_LLIB:=C0DL.OBJ C0FL.OBJ C0L.OBJ CL.LIB MATHL.LIB
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)LIB/%,$(ARCHIVE_BCP30AF_LLIB))
$(patsubst %,$(DSTDIR_BCP30AF)LIB/%,$(ARCHIVE_BCP30AF_LLIB)) &: osdisks/bcp30axx/LLIB.ZIP
	install -D -d $(DSTDIR_BCP30AF)LIB/
	unzip -DD -o -d $(DSTDIR_BCP30AF)LIB/ $<

ARCHIVE_BCP30AF_MATHSRC:=ACOSASIN.CAS ACOSSINL.CAS ATAN.CAS ATAN2.CAS ATAN2L.CAS ATANL.CAS ATOF.C ATOLD.C CEIL.CAS CEILL.CAS CLEAR87.CAS COS.CAS COSH.CAS COSHL.CAS COSL.CAS CTRL87.CAS DIFFTIME.C EFCVT.C EMUVARS.ASM EMUVARS.H EXP.CAS EXPL.CAS EXPLD.CAS FABS.CAS FABSL.CAS FBSTP.ASM FLAGS87.ASM FLOOR.CAS FLOORL.CAS FMOD.CAS FMODL.CAS FPERR.C FPRESET.C FREXP.CAS FREXPL.CAS FTOL.ASM GCVT.C HUGEVAL.C HYPOT.CAS HYPOTL.CAS LDEXP.CAS LDEXPL.CAS LDTRUNC.CAS LOG.CAS LOG10.CAS LOG10L.CAS LOGL.CAS MATH.MAK MATHERR.C MATHERRL.C MATHOBJ.MAK MATHWHY.C MODF.CAS MODFL.CAS POLY.CAS POLYL.CAS POW.CAS POW10D.C POW10L.C POWL.CAS REALCVT.CAS ROUND.CAS SCANTOD.CAS SIN.CAS SINH.CAS SINHL.CAS SINL.CAS SQRT.CAS SQRTL.CAS STAT87.CAS STRTOD.C TAN.CAS TANH.CAS TANHL.CAS TANL.CAS WINTRANS.ASM XCVT.CAS _MATHERL.C _MATHERR.C _POW10.CAS
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)CRTL/MATH/%,$(ARCHIVE_BCP30AF_MATHSRC))
$(patsubst %,$(DSTDIR_BCP30AF)CRTL/MATH/%,$(ARCHIVE_BCP30AF_MATHSRC)) &: osdisks/bcp30axx/MATHSRC.ZIP
	install -D -d $(DSTDIR_BCP30AF)CRTL/MATH/
	unzip -DD -o -d $(DSTDIR_BCP30AF)CRTL/MATH/ $<

ARCHIVE_BCP30AF_MFILEAPP:=MAKEFILE MFILEAPP.CPP MFILEAPP.H MFILEAPP.PRJ MFILEAPP.RC MFILEAPP.RES
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/MFILEAPP/%,$(ARCHIVE_BCP30AF_MFILEAPP))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/MFILEAPP/%,$(ARCHIVE_BCP30AF_MFILEAPP)) &: osdisks/bcp30axx/MFILEAPP.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/MFILEAPP/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/MFILEAPP/ $<

ARCHIVE_BCP30AF_MLIB:=C0DM.OBJ C0FM.OBJ C0M.OBJ CM.LIB MATHM.LIB
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)LIB/%,$(ARCHIVE_BCP30AF_MLIB))
$(patsubst %,$(DSTDIR_BCP30AF)LIB/%,$(ARCHIVE_BCP30AF_MLIB)) &: osdisks/bcp30axx/MLIB.ZIP
	install -D -d $(DSTDIR_BCP30AF)LIB/
	unzip -DD -o -d $(DSTDIR_BCP30AF)LIB/ $<

ARCHIVE_BCP30AF_OWL:=BUILDOWL.BAT
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/%,$(ARCHIVE_BCP30AF_OWL))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/%,$(ARCHIVE_BCP30AF_OWL)) &: osdisks/bcp30axx/OWL.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/ $<

ARCHIVE_BCP30AF_OWLDEMOS:=BSCRLAPP.CPP BSCRLAPP.PRJ BSCRLAPP.RC BSCRLAPP.RES BTNTEST.CPP BTNTEST.PRJ CALLDLL.CPP CALLDLL.H CALLDLL.PRJ CALLDLL.RC CALLDLL.RES CBOXTEST.CPP CBOXTEST.PRJ CBXTTEST.CPP CBXTTEST.PRJ CCTLTEST.CPP CCTLTEST.H CCTLTEST.PRJ CCTLTEST.RC CCTLTEST.RES CDLGDLL.CPP CDLGDLL.DEF CDLGDLL.H CDLGDLL.PRJ CDLGDLL.RC CDLGDLL.RES COLORDLG.CPP COLORDLG.DLG COLORDLG.H COLORDLG.RCH CURSAPP.CPP CURSAPP.PRJ DCTLTEST.CPP DCTLTEST.H DCTLTEST.PRJ DCTLTEST.RC DCTLTEST.RES DIALTEST.CPP DIALTEST.H DIALTEST.PRJ DIALTEST.RC DIALTEST.RES DLLHELLO.CPP DLLHELLO.DEF DLLHELLO.H DLLHELLO.PRJ EDITAPP.CPP EDITAPP.PRJ EDITAPP.RC EDITAPP.RES EDITTEST.CPP EDITTEST.PRJ EWNDTEST.CPP EWNDTEST.H EWNDTEST.PRJ EWNDTEST.RC EWNDTEST.RES GBOXTEST.CPP GBOXTEST.PRJ HELLOAPP.CPP HELLOAPP.PRJ INSTTEST.CPP INSTTEST.PRJ LBOXTEST.CPP LBOXTEST.PRJ LBXTTEST.CPP LBXTTEST.PRJ MAKEFILE MAKEFILE.INC MDIAPP.CPP MDIAPP.PRJ MDIAPP.RC MDIAPP.RES MDITEST.CPP MDITEST.H MDITEST.PRJ MDITEST.RC MDITEST.RES MLBXTTST.CPP MLBXTTST.PRJ NOTITEST.CPP NOTITEST.H NOTITEST.PRJ NOTITEST.RC NOTITEST.RES PALTEST.CPP PALTEST.DLG PALTEST.H PALTEST.PRJ PALTEST.RC PALTEST.RES POPUP.CPP POPUP.PRJ POPUP.RC POPUP.RES SBARTEST.CPP SBARTEST.PRJ SCRIBAPP.CPP SCRIBAPP.PRJ SCROLAPP.CPP SCROLAPP.PRJ STATTEST.CPP STATTEST.PRJ TRANTEST.CPP TRANTEST.H TRANTEST.PRJ TRANTEST.RC TRANTEST.RES USECDLL.CPP USECDLL.H USECDLL.PRJ USECDLL.RC USECDLL.RES USECDLL2.CPP USECDLL2.H USECDLL2.PRJ USECDLL2.RC USECDLL2.RES VDLGAPP.CPP VDLGAPP.PRJ VDLGAPP.RC VDLGAPP.RES
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/%,$(ARCHIVE_BCP30AF_OWLDEMOS))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/%,$(ARCHIVE_BCP30AF_OWLDEMOS)) &: osdisks/bcp30axx/OWLDEMOS.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/ $<

ARCHIVE_BCP30AF_OWLDOC:=BWCC-OWL.DOC HELPME!.DOC OWL.DOC OWLDLL.DOC
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/DOC/%,$(ARCHIVE_BCP30AF_OWLDOC))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/DOC/%,$(ARCHIVE_BCP30AF_OWLDOC)) &: osdisks/bcp30axx/OWLDOC.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/DOC/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/DOC/ $<

ARCHIVE_BCP30AF_OWLINC:=APPDICT.H APPLICAT.H BBUTTON.H BCHKBOX.H BDIVIDER.H BGRPBOX.H BRADIO.H BSTATBMP.H BSTATIC.H BUTTON.H BWINDOW.H CHECKBOX.H COMBOBOX.H CONTROL.H DIALOG.H EDIT.H EDITACC.RC EDITMENU.RC EDITWND.H FILEACC.RC FILEDIAL.DLG FILEDIAL.H FILEMENU.RC FILEWND.H GROUPBOX.H INPUTDIA.DLG INPUTDIA.H LISTBOX.H MDI.H MODULE.H OBJSTRM.H OWL.H OWLDEFS.H OWLRC.H RADIOBUT.H SAFEPOOL.H SCROLLBA.H SCROLLER.H STATIC.H STDWNDS.DLG TCOLLECT.H WINDOBJ.H WINDOW.H
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/INCLUDE/%,$(ARCHIVE_BCP30AF_OWLINC))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/INCLUDE/%,$(ARCHIVE_BCP30AF_OWLINC)) &: osdisks/bcp30axx/OWLINC.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/INCLUDE/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/INCLUDE/ $<

ARCHIVE_BCP30AF_OWLLIB:=OWL.DEF OWL.LIB OWLDLL.DEF OWLWC.LIB OWLWL.LIB OWLWM.LIB OWLWS.LIB
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/LIB/%,$(ARCHIVE_BCP30AF_OWLLIB))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/LIB/%,$(ARCHIVE_BCP30AF_OWLLIB)) &: osdisks/bcp30axx/OWLLIB.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/LIB/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/LIB/ $<

ARCHIVE_BCP30AF_OWLSRC:=APPDICT.CPP APPLICAT.CPP BBUTTON.CPP BCHKBOX.CPP BDIVIDER.CPP BGRPBOX.CPP BRADIO.CPP BSTATBMP.CPP BSTATIC.CPP BUTTON.CPP BWINDOW.CPP CHECKBOX.CPP COMBOBOX.CPP CONTROL.CPP DIALOG.CPP EDIT.CPP EDITWND.CPP FILEDIAL.CPP FILEWND.CPP GROUPBOX.CPP INPUTDIA.CPP LISTBOX.CPP MAKEFILE MDICLIEN.CPP MDIFRAME.CPP MODULE.CPP OBJSTRM.CPP OWL.CPP OWLDLL.DEF OWLMATH.CPP RADIOBUT.CPP SAFEPOOL.CPP SCROLLBA.CPP SCROLLER.CPP STATIC.CPP SWINDOBJ.CPP TCOLLECT.CPP TSORTCOL.CPP WINDOBJ.CPP WINDOW.CPP
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/SOURCE/%,$(ARCHIVE_BCP30AF_OWLSRC))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/SOURCE/%,$(ARCHIVE_BCP30AF_OWLSRC)) &: osdisks/bcp30axx/OWLSRC.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/SOURCE/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/SOURCE/ $<

ARCHIVE_BCP30AF_PAINT:=ELLIPSE.CUR ELLIPSE.ICO FELLIPSE.CUR FELLIPSE.ICO FILL.CUR FILL.ICO FRECT.CUR FRECT.ICO MAKEFILE OWLPAINT.ICO PAINT.CPP PAINT.PRJ PAINT.RC PAINT.RES PEN.CUR PEN.ICO RECT.CUR RECT.ICO
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/PAINT/%,$(ARCHIVE_BCP30AF_PAINT))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/PAINT/%,$(ARCHIVE_BCP30AF_PAINT)) &: osdisks/bcp30axx/PAINT.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/PAINT/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/PAINT/ $<

ARCHIVE_BCP30AF_PROGTALK:=DDECLIEN.CPP DDECLIEN.H MAKEFILE PROGTALK.CPP PROGTALK.H PROGTALK.PRJ PROGTALK.RC PROGTALK.RES
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/PROGTALK/%,$(ARCHIVE_BCP30AF_PROGTALK))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/PROGTALK/%,$(ARCHIVE_BCP30AF_PROGTALK)) &: osdisks/bcp30axx/PROGTALK.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/PROGTALK/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/PROGTALK/ $<

ARCHIVE_BCP30AF_QUEUE:=LIST.ASM LIST.ASO NODE.ASM NODE.ASO OOP.ASM QUEUE.ASM QUEUE.ASO STACK.ASM STACK.ASO
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/TASM/QUEUE/%,$(ARCHIVE_BCP30AF_QUEUE))
$(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/TASM/QUEUE/%,$(ARCHIVE_BCP30AF_QUEUE)) &: osdisks/bcp30axx/QUEUE.ZIP
	install -D -d $(DSTDIR_BCP30AF)EXAMPLES/TASM/QUEUE/
	unzip -DD -o -d $(DSTDIR_BCP30AF)EXAMPLES/TASM/QUEUE/ $<

ARCHIVE_BCP30AF_RTLINSRC:=ASMRULES.H FAKEIEEE.H FILESYS.H INSTDATA.H IOCONFIG.H MATHERR.ASI RTLDATA.H RULES.ASI RULES.H SUBALLOC.H USER.H _DIR.H _FARFUNC.H _FHEAP.H _GRAPH.H _HEAP.H _HEAP.INC _IO.H _MATH.H _NFILE.H _PRINTF.H _PROCESS.H _SCANF.H _STDIO.H _VIDEO.H _WIN.H
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)CRTL/RTLINC/%,$(ARCHIVE_BCP30AF_RTLINSRC))
$(patsubst %,$(DSTDIR_BCP30AF)CRTL/RTLINC/%,$(ARCHIVE_BCP30AF_RTLINSRC)) &: osdisks/bcp30axx/RTLINSRC.ZIP
	install -D -d $(DSTDIR_BCP30AF)CRTL/RTLINC/
	unzip -DD -o -d $(DSTDIR_BCP30AF)CRTL/RTLINC/ $<

ARCHIVE_BCP30AF_RW:=LOADBWCC.EXE WORKED1.DLL WORKED2.DLL WORKED3.DLL WORKED4.DLL WORKED5.DLL WORKHELP.HLP WORKLIB1.DLL WORKLIB2.DLL WORKSHOP.EXE
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_RW))
$(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_RW)) &: osdisks/bcp30axx/RW.ZIP
	install -D -d $(DSTDIR_BCP30AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP30AF)BIN/ $<

ARCHIVE_BCP30AF_RWCDEMO:=BITBNAPP.C BITBNAPP.RES BITBTN.C BITBTN.DEF BITBTN.PRJ BITBTN.RES BITBTNCO.H BTNBNAPP.PRJ RWCDEMO.CPP RWCDEMO.DEF RWCDEMO.H RWCDEMO.PRJ RWCDEMO.RC RWCDEMO.RES RWCDEMOB.PRJ RWCDEMOB.RC RWCDEMOB.RES RWCDEMOC.H RWCDLG.CPP RWCDLG.H RWCWND.CPP RWCWND.H RWDEMO.CUR RWDEMO.ICO STATBAR.BMP STATLINE.BMP
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/WORKSHOP/%,$(ARCHIVE_BCP30AF_RWCDEMO))
$(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/WORKSHOP/%,$(ARCHIVE_BCP30AF_RWCDEMO)) &: osdisks/bcp30axx/RWCDEMO.ZIP
	install -D -d $(DSTDIR_BCP30AF)EXAMPLES/WORKSHOP/
	unzip -DD -o -d $(DSTDIR_BCP30AF)EXAMPLES/WORKSHOP/ $<

ARCHIVE_BCP30AF_RWDOC:=BWCCAPI.RW BWCCSTYL.RW CUSTCNTL.RW MANUAL.RW
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)DOC/%,$(ARCHIVE_BCP30AF_RWDOC))
$(patsubst %,$(DSTDIR_BCP30AF)DOC/%,$(ARCHIVE_BCP30AF_RWDOC)) &: osdisks/bcp30axx/RWDOC.ZIP
	install -D -d $(DSTDIR_BCP30AF)DOC/
	unzip -DD -o -d $(DSTDIR_BCP30AF)DOC/ $<

ARCHIVE_BCP30AF_SLIB:=C0DS.OBJ C0FS.OBJ C0FT.OBJ C0S.OBJ C0T.OBJ CS.LIB MATHS.LIB
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)LIB/%,$(ARCHIVE_BCP30AF_SLIB))
$(patsubst %,$(DSTDIR_BCP30AF)LIB/%,$(ARCHIVE_BCP30AF_SLIB)) &: osdisks/bcp30axx/SLIB.ZIP
	install -D -d $(DSTDIR_BCP30AF)LIB/
	unzip -DD -o -d $(DSTDIR_BCP30AF)LIB/ $<

ARCHIVE_BCP30AF_STARTUP:=BUILD-C0.BAT C0.ASM C0D.ASM C0W.ASM RULES.ASI
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)LIB/STARTUP/%,$(ARCHIVE_BCP30AF_STARTUP))
$(patsubst %,$(DSTDIR_BCP30AF)LIB/STARTUP/%,$(ARCHIVE_BCP30AF_STARTUP)) &: osdisks/bcp30axx/STARTUP.ZIP
	install -D -d $(DSTDIR_BCP30AF)LIB/STARTUP/
	unzip -DD -o -d $(DSTDIR_BCP30AF)LIB/STARTUP/ $<

ARCHIVE_BCP30AF_STEPS:=HELPWIND.CPP HELPWIND.DEF HELPWIND.H MAKEFILE STEP1.CPP STEP1.PRJ STEP10.CPP STEP10.PRJ STEP2.CPP STEP2.PRJ STEP3.CPP STEP3.PRJ STEP4.CPP STEP4.PRJ STEP5.CPP STEP5.PRJ STEP6.CPP STEP6.PRJ STEP7.CPP STEP7.PRJ STEP8.CPP STEP8.PRJ STEP9.CPP STEP9.PRJ STEPS.DEF STEPS.H STEPS.RC STEPS.RES
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/STEPS/%,$(ARCHIVE_BCP30AF_STEPS))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/STEPS/%,$(ARCHIVE_BCP30AF_STEPS)) &: osdisks/bcp30axx/STEPS.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/STEPS/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/STEPS/ $<

ARCHIVE_BCP30AF_SYSINFO:=MAKEFILE SYSINFO.CPP SYSINFO.H SYSINFO.PRJ SYSINFO.RC SYSINFO.RES
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/SYSINFO/%,$(ARCHIVE_BCP30AF_SYSINFO))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/SYSINFO/%,$(ARCHIVE_BCP30AF_SYSINFO)) &: osdisks/bcp30axx/SYSINFO.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/SYSINFO/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/SYSINFO/ $<

ARCHIVE_BCP30AF_TASM:=H2ASH.EXE TASM.EXE TASM.TAH TASMX.EXE TCREF.EXE
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_TASM))
$(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_TASM)) &: osdisks/bcp30axx/TASM.ZIP
	install -D -d $(DSTDIR_BCP30AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP30AF)BIN/ $<

ARCHIVE_BCP30AF_TASMEXMP:=ASMPSCL.ASM AVERAGE.ASM BIOS.INC CALCAVG.CPP CALLCT.CPP CALLPROC.ASM CASMLINK.ASM COMPROG.ASM CONCISE.ASM COUNT.ASM COUNTADD.ASM COUNTADD.CPP COUNTLG.ASM CSPEC.ASM DBLCOLON.ASM DLLPROG.ASM DOS.INC DOTOTAL.ASM ENVMOD.ASM ENVSTR.PAS EXCHMOD.ASM EXEPROG.ASM FINDCHAR.ASM HELLO1.ASM HELLO2.ASM HELLO3.ASM HEX.ASM HEX.PAS HEXMOD.ASM KBD.INC LINK2ASM.CPP MBIOS.MAC MDOS.MAC MMACROS.MAC PRIMES.ASM PRMSTACK.ASM REVERSE.ASM SHOWTOT.CPP SOMESTR.ASM VAREXCH.ASM VAREXCH.PAS WINPROG.ASM
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/TASM/%,$(ARCHIVE_BCP30AF_TASMEXMP))
$(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/TASM/%,$(ARCHIVE_BCP30AF_TASMEXMP)) &: osdisks/bcp30axx/TASMEXMP.ZIP
	install -D -d $(DSTDIR_BCP30AF)EXAMPLES/TASM/
	unzip -DD -o -d $(DSTDIR_BCP30AF)EXAMPLES/TASM/ $<

ARCHIVE_BCP30AF_TCALC:=TCALC.C TCALC.DOC TCALC.H TCALC.PRJ TCDISPLY.C TCINPUT.C TCOMMAND.C TCPARSER.C TCUTIL.C
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/TCALC/%,$(ARCHIVE_BCP30AF_TCALC))
$(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/TCALC/%,$(ARCHIVE_BCP30AF_TCALC)) &: osdisks/bcp30axx/TCALC.ZIP
	install -D -d $(DSTDIR_BCP30AF)EXAMPLES/TCALC/
	unzip -DD -o -d $(DSTDIR_BCP30AF)EXAMPLES/TCALC/ $<

ARCHIVE_BCP30AF_TD:=TD.EXE TD286.EXE TD386.EXE
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_TD))
$(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_TD)) &: osdisks/bcp30axx/TD.ZIP
	install -D -d $(DSTDIR_BCP30AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP30AF)BIN/ $<

ARCHIVE_BCP30AF_TDEXMPL:=BCDEMO.C BCDEMO.EXE BCDEMOB.C BCDEMOB.EXE
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/TD/%,$(ARCHIVE_BCP30AF_TDEXMPL))
$(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/TD/%,$(ARCHIVE_BCP30AF_TDEXMPL)) &: osdisks/bcp30axx/TDEXMPL.ZIP
	install -D -d $(DSTDIR_BCP30AF)EXAMPLES/TD/
	unzip -DD -o -d $(DSTDIR_BCP30AF)EXAMPLES/TD/ $<

ARCHIVE_BCP30AF_TDUTIL:=TD286INS.EXE TDDEV.EXE TDH386.SYS TDHELP.TDH TDINST.EXE TDMAP.EXE TDMEM.EXE TDNMI.COM TDREMOTE.EXE TDRF.EXE TDSTRIP.EXE TDUMP.EXE
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_TDUTIL))
$(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_TDUTIL)) &: osdisks/bcp30axx/TDUTIL.ZIP
	install -D -d $(DSTDIR_BCP30AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP30AF)BIN/ $<

ARCHIVE_BCP30AF_TDW:=TDDEBUG.386 TDW.EXE TDWHELP.TDH TDWINST.EXE WINDEBUG.DLL WREMOTE.EXE WRSETUP.EXE
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_TDW))
$(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_TDW)) &: osdisks/bcp30axx/TDW.ZIP
	install -D -d $(DSTDIR_BCP30AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP30AF)BIN/ $<

ARCHIVE_BCP30AF_TDWEXMPL:=BCWDEMO.C BCWDEMO.DEF BCWDEMO.EXE BCWDEMO.H BCWDEMO.ICO BCWDEMO.PRJ BCWDEMO.RC BCWDEMO.RES BCWDEMOA.C BCWDEMOA.EXE BCWDEMOA.PRJ BCWDEMOB.C BCWDEMOB.EXE BCWDEMOB.PRJ TDODEMO.CPP TDODEMO.DEF TDODEMO.EXE TDODEMO.H TDODEMO.ICO TDODEMO.PRJ TDODEMO.RC TDODEMO.RES TDODEMOB.CPP TDODEMOB.EXE TDODEMOB.H TDODEMOB.PRJ
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/TD/%,$(ARCHIVE_BCP30AF_TDWEXMPL))
$(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/TD/%,$(ARCHIVE_BCP30AF_TDWEXMPL)) &: osdisks/bcp30axx/TDWEXMPL.ZIP
	install -D -d $(DSTDIR_BCP30AF)EXAMPLES/TD/
	unzip -DD -o -d $(DSTDIR_BCP30AF)EXAMPLES/TD/ $<

ARCHIVE_BCP30AF_TFEXMPL:=CALLTEST.C CALLTEST.EXE PLOST.C PLOST.EXE PRIME0.C PRIME0.EXE PRIME1.C PRIME1.EXE PRIME2.C PRIME2.EXE PRIME3.C PRIME3.EXE PRIME4.C PRIME4.EXE PRIME5.C PRIME5.EXE PRIME6.C PRIME6.EXE PTOLL.C PTOLL.EXE
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/TPROF/%,$(ARCHIVE_BCP30AF_TFEXMPL))
$(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/TPROF/%,$(ARCHIVE_BCP30AF_TFEXMPL)) &: osdisks/bcp30axx/TFEXMPL.ZIP
	install -D -d $(DSTDIR_BCP30AF)EXAMPLES/TPROF/
	unzip -DD -o -d $(DSTDIR_BCP30AF)EXAMPLES/TPROF/ $<

#ARCHIVE_BCP30AF_TPROF:=TDH386.SYS TF386.EXE TFHELP.TFH TFINST.EXE TFREMOTE.EXE TPROF.EXE
ARCHIVE_BCP30AF_TPROF:=TF386.EXE TFHELP.TFH TFINST.EXE TFREMOTE.EXE TPROF.EXE
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_TPROF))
$(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_TPROF)) &: osdisks/bcp30axx/TPROF.ZIP
	install -D -d $(DSTDIR_BCP30AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP30AF)BIN/ $< $(ARCHIVE_BCP30AF_TPROF)

ARCHIVE_BCP30AF_TPROFW:=TFWHELP.TFH TPROFW.EXE
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_TPROFW))
$(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_TPROFW)) &: osdisks/bcp30axx/TPROFW.ZIP
	install -D -d $(DSTDIR_BCP30AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP30AF)BIN/ $<

ARCHIVE_BCP30AF_TTT:=MAKEFILE TTT.CPP TTT.H TTT.ICO TTT.PRJ TTT.RC TTT.RES
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/TTT/%,$(ARCHIVE_BCP30AF_TTT))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/EXAMPLES/TTT/%,$(ARCHIVE_BCP30AF_TTT)) &: osdisks/bcp30axx/TTT.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/TTT/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/EXAMPLES/TTT/ $<

ARCHIVE_BCP30AF_TVDEMOS:=ASCII.CPP ASCII.H CALC.CPP CALC.H CALENDAR.CPP CALENDAR.H DATACOLL.CPP DATACOLL.H DEMOHELP.H DEMOHELP.HLP FIELDS.CPP FIELDS.H FILEVIEW.CPP FILEVIEW.H FILEVIEW.PRJ FORMCMDS.H FORMS.CPP FORMS.H FVIEWER.CPP GADGETS.CPP GADGETS.H GENFORM.CPP GENFORMS.MAK GENPARTS.H GENPHONE.H GRAPHAPP.CPP GRAPHAPP.H HELLO.CPP HELLO.PRJ LISTDLG.CPP LISTDLG.H MOUSEDLG.CPP MOUSEDLG.H PUZZLE.CPP PUZZLE.H TVBGI.CPP TVBGI.H TVBGI.PRJ TVCMDS.H TVDEMO.H TVDEMO.PRJ TVDEMO1.CPP TVDEMO2.CPP TVDEMO3.CPP TVEDIT.H TVEDIT.PRJ TVEDIT1.CPP TVEDIT2.CPP TVEDIT3.CPP TVFORMS.CPP TVFORMS.PRJ TVTXTDMO.CPP TVTXTDMO.PRJ
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)TVISION/DEMOS/%,$(ARCHIVE_BCP30AF_TVDEMOS))
$(patsubst %,$(DSTDIR_BCP30AF)TVISION/DEMOS/%,$(ARCHIVE_BCP30AF_TVDEMOS)) &: osdisks/bcp30axx/TVDEMOS.ZIP
	install -D -d $(DSTDIR_BCP30AF)TVISION/DEMOS/
	unzip -DD -o -d $(DSTDIR_BCP30AF)TVISION/DEMOS/ $<

ARCHIVE_BCP30AF_TVDOCDEM:=TVG17B.CPP TVG17B.PRJ TVGUID01.CPP TVGUID01.PRJ TVGUID02.CPP TVGUID02.PRJ TVGUID03.CPP TVGUID03.PRJ TVGUID04.CPP TVGUID04.PRJ TVGUID05.CPP TVGUID05.PRJ TVGUID06.CPP TVGUID06.PRJ TVGUID07.CPP TVGUID07.PRJ TVGUID08.CPP TVGUID08.PRJ TVGUID09.CPP TVGUID09.PRJ TVGUID10.CPP TVGUID10.PRJ TVGUID11.CPP TVGUID11.PRJ TVGUID12.CPP TVGUID12.PRJ TVGUID13.CPP TVGUID13.PRJ TVGUID14.CPP TVGUID14.PRJ TVGUID15.CPP TVGUID15.PRJ TVGUID16.CPP TVGUID16.PRJ TVGUID17.CPP TVGUID17.PRJ TVGUID18.CPP TVGUID18.PRJ TVGUID19.CPP TVGUID19.PRJ TVGUID20.CPP TVGUID20.PRJ TVGUID21.CPP TVGUID21.PRJ
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)TVISION/DOCDEMOS/%,$(ARCHIVE_BCP30AF_TVDOCDEM))
$(patsubst %,$(DSTDIR_BCP30AF)TVISION/DOCDEMOS/%,$(ARCHIVE_BCP30AF_TVDOCDEM)) &: osdisks/bcp30axx/TVDOCDEM.ZIP
	install -D -d $(DSTDIR_BCP30AF)TVISION/DOCDEMOS/
	unzip -DD -o -d $(DSTDIR_BCP30AF)TVISION/DOCDEMOS/ $<

ARCHIVE_BCP30AF_TVHELP:=DEMOHELP.TXT HELP.CPP TVHC.CPP TVHC.EXE TVHC.H TVHC.PRJ
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)TVISION/HELP/%,$(ARCHIVE_BCP30AF_TVHELP))
$(patsubst %,$(DSTDIR_BCP30AF)TVISION/HELP/%,$(ARCHIVE_BCP30AF_TVHELP)) &: osdisks/bcp30axx/TVHELP.ZIP
	install -D -d $(DSTDIR_BCP30AF)TVISION/HELP/
	unzip -DD -o -d $(DSTDIR_BCP30AF)TVISION/HELP/ $<

ARCHIVE_BCP30AF_TVINC:=APP.H BUFFERS.H COLORSEL.H CONFIG.H DIALOGS.H DRAWBUF.H EDITORS.H HELP.H MENUS.H MSGBOX.H OBJECTS.H RESOURCE.H STDDLG.H SYSTEM.H TEXTVIEW.H TKEYS.H TOBJSTRM.H TTYPES.H TV.H TVOBJS.H UTIL.H VIEWS.H
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)TVISION/INCLUDE/%,$(ARCHIVE_BCP30AF_TVINC))
$(patsubst %,$(DSTDIR_BCP30AF)TVISION/INCLUDE/%,$(ARCHIVE_BCP30AF_TVINC)) &: osdisks/bcp30axx/TVINC.ZIP
	install -D -d $(DSTDIR_BCP30AF)TVISION/INCLUDE/
	unzip -DD -o -d $(DSTDIR_BCP30AF)TVISION/INCLUDE/ $<

ARCHIVE_BCP30AF_TVLIB:=TV.LIB
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)TVISION/LIB/%,$(ARCHIVE_BCP30AF_TVLIB))
$(patsubst %,$(DSTDIR_BCP30AF)TVISION/LIB/%,$(ARCHIVE_BCP30AF_TVLIB)) &: osdisks/bcp30axx/TVLIB.ZIP
	install -D -d $(DSTDIR_BCP30AF)TVISION/LIB/
	unzip -DD -o -d $(DSTDIR_BCP30AF)TVISION/LIB/ $<

ARCHIVE_BCP30AF_TVSRC:=COLORSEL.CPP DRIVERS.CPP DRIVERS2.CPP EDITS.ASM EDITSTAT.CPP FRAMELIN.ASM GENINC.CPP GRP.CPP HISTLIST.CPP MAKEFILE MAPCOLOR.CPP MENU.CPP MISC.CPP MSGBOX.CPP NEW.CPP NEWSTR.CPP NMBKGRND.CPP NMBUTTON.CPP NMCHDRDL.CPP NMCHKBOX.CPP NMCLRSEL.CPP NMCLUSTR.CPP NMCOLLCT.CPP NMDIALOG.CPP NMDIRBOX.CPP NMDIRCOL.CPP NMDSKTOP.CPP NMEDITOR.CPP NMFILCOL.CPP NMFILDLG.CPP NMFILLST.CPP NMFRAME.CPP NMGROUP.CPP NMHIST.CPP NMINPTLN.CPP NMLABEL.CPP NMLSTBOX.CPP NMLSTVWR.CPP NMMNUBAR.CPP NMMNUBOX.CPP NMMNUVW.CPP NMPRMTXT.CPP NMRBTNS.CPP NMRESCOL.CPP NMSCOLL.CPP NMSCRBAR.CPP NMSCROLL.CPP NMSTCTXT.CPP NMSTDDLG.CPP NMSTLINE.CPP NMSTRCOL.CPP NMSTRLST.CPP NMVIEW.CPP NMWINDOW.CPP PALETTE.CPP SBKGRND.CPP SBUTTON.CPP SCHDRDLG.CPP SCHECKBO.CPP SCLRSEL.CPP SCLUSTER.CPP SDESKTOP.CPP SDIALOG.CPP SDIRCOLL.CPP SDIRLIST.CPP SEDITORS.CPP SFILCOLL.CPP SFILDLG.CPP SFILELST.CPP SFINFPNE.CPP SFINPUTL.CPP SFRAME.CPP SGROUP.CPP SHISTORY.CPP SINPUTLI.CPP SLABEL.CPP SLISTBOX.CPP SLSTVIEW.CPP SMENUBAR.CPP SMENUBOX.CPP SMNUVIEW.CPP SPARAMTE.CPP SRADIOBU.CPP SRESCOLL.CPP SSCRLBAR.CPP SSCROLLE.CPP SSTATICT.CPP SSTATUSL.CPP SSTRCOLL.CPP SSTRLST.CPP STDDLG.CPP STRMSTAT.CPP SVIEW.CPP SWAPST.ASM SWINDOW.CPP SYSERR.CPP SYSINT.ASM TAPPLICA.CPP TBKGRND.CPP TBUTTON.CPP TCHDRDLG.CPP TCHECKBO.CPP TCLUSTER.CPP TCMDSET.CPP TCOLLECT.CPP TDESKTOP.CPP TDIALOG.CPP TDIRCOLL.CPP TDIRLIST.CPP TEDITOR1.CPP TEDITOR2.CPP TEDITWND.CPP TEVENT.CPP TEXTVIEW.CPP TFILDLG.CPP TFILECOL.CPP TFILEDTR.CPP TFILLIST.CPP TFRAME.CPP TGRMV.ASM TGROUP.CPP THISTORY.CPP THISTWIN.CPP THSTVIEW.CPP TINDICTR.CPP TINPUTLI.CPP TLABEL.CPP TLISTBOX.CPP TLSTVIEW.CPP TMEMO.CPP TMENUBAR.CPP TMENUBOX.CPP TMNUVIEW.CPP TMOUSE.CPP TOBJECT.CPP TOBJSTRM.CPP TPARAMTE.CPP TPOINT.CPP TPROGRAM.CPP TRADIOBU.CPP TRESCOLL.CPP TRESFILE.CPP TSCREEN.CPP TSCRLBAR.CPP TSCROLLE.CPP TSORTCOL.CPP TSTATICT.CPP TSTATUSL.CPP TSTRCOLL.CPP TSTRLIST.CPP TTPRVLNS.ASM TVCURSOR.ASM TVEXPOSD.ASM TVIEW.CPP TVLIB.RSP TVTEXT1.CPP TVTEXT2.CPP TVWRITE.ASM TVWRITE.INC TWINDOW.CPP
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)TVISION/SOURCE/%,$(ARCHIVE_BCP30AF_TVSRC))
$(patsubst %,$(DSTDIR_BCP30AF)TVISION/SOURCE/%,$(ARCHIVE_BCP30AF_TVSRC)) &: osdisks/bcp30axx/TVSRC.ZIP
	install -D -d $(DSTDIR_BCP30AF)TVISION/SOURCE/
	unzip -DD -o -d $(DSTDIR_BCP30AF)TVISION/SOURCE/ $<

ARCHIVE_BCP30AF_WBIN:=ATI.DLL BC.ICO BC.PIF FCONVERT.EXE GROUPS.EXE HC.EXE IMPLIBW.EXE RC.EXE RC2MSG.EXE RCPP.ERR RCPP.EXE TBROWSER.DLL TCW.EXE TOOLHELP.DLL TSENG.DLL WINSIGHT.EXE WINSIGHT.HLP WINSTUB.EXE WSIHOOK.DLL WSIWIN.DLL
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_WBIN))
$(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_WBIN)) &: osdisks/bcp30axx/WBIN.ZIP
	install -D -d $(DSTDIR_BCP30AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP30AF)BIN/ $<

ARCHIVE_BCP30AF_WCOBJ:=VERSION.OBJ
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/OBJECT/WC/%,$(ARCHIVE_BCP30AF_WCOBJ))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/OBJECT/WC/%,$(ARCHIVE_BCP30AF_WCOBJ)) &: osdisks/bcp30axx/WCOBJ.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/OBJECT/WC/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/OBJECT/WC/ $<

ARCHIVE_BCP30AF_WEXAMPLE:=BITMAP.CPP BITMAP.DEF BITMAP.H BITMAP.PRJ BITMAP.RC BITMAP.RES BULLET.BMP CHKBOFF.BMP CHKBON.BMP CODEC.BMP CONTINUE.BMP DDECLNT.C DDECLNT.H DDESRVR.C DDESRVR.H DLLDEMO.CPP DLLDEMO.DEF DLLDEMO.ICO DLLDEMO.PRJ DLLDEMO.RC DLLDEMO.RES DLLDEMO1.BMP DLLDEMO2.BMP DLLSHELL.CPP DONE.BMP FFIND.C FFIND.DEF FFIND.H FFIND.ICO FFIND.PRJ FFIND.RC FFIND.RES HDUMP.C HDUMP.DEF HDUMP.H HDUMP.ICO HDUMP.PRJ HDUMP.RC HDUMP.RES HELP.CUR HELPEX.C HELPEX.DEF HELPEX.DLG HELPEX.H HELPEX.HLP HELPEX.HPJ HELPEX.PH HELPEX.PRJ HELPEX.RC HELPEX.RES HELPEX.RTF HELPICON.BMP HELPIDS.H KEYS.RTF MAX2ICON.BMP MOUSE.BMP MSGPROC.C MSGPROC.H MSGWND.C MSGWND.DEF MSGWND.H MSGWND.ICO MSGWND.PRJ MSGWND.RC MSGWND.RES TERMS.RTF TODO.DEF TODO.PRJ TODODEFS.H TODODLGS.CPP TODODLGS.H TODOLIST.CPP TODOLIST.H TODOWIN.CPP TODOWIN.H TODOWIN.RC TODOWIN.RES TSTAPP.C TSTAPP.DEF TSTAPP.H TSTAPP.ICO TSTAPP.PRJ TSTAPP.RC TSTAPP.RES WHELLO.CPP WHELLO.DEF WHELLO.ICO WHELLO.MAK WHELLO.PRJ WHELLO.RC WHELLO.RES WINWORD.BMP
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/%,$(ARCHIVE_BCP30AF_WEXAMPLE))
$(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/%,$(ARCHIVE_BCP30AF_WEXAMPLE)) &: osdisks/bcp30axx/WEXAMPLE.ZIP
	install -D -d $(DSTDIR_BCP30AF)EXAMPLES/
	unzip -DD -o -d $(DSTDIR_BCP30AF)EXAMPLES/ $<

ARCHIVE_BCP30AF_WHELP1:=OWLHELP.TCH TCHELP.TCH THELP.COM TVCHELP.TCH
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_WHELP1))
$(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_WHELP1)) &: osdisks/bcp30axx/WHELP1.ZIP
	install -D -d $(DSTDIR_BCP30AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP30AF)BIN/ $<

ARCHIVE_BCP30AF_WHELP2:=TCWHELP.HLP
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_WHELP2))
$(patsubst %,$(DSTDIR_BCP30AF)BIN/%,$(ARCHIVE_BCP30AF_WHELP2)) &: osdisks/bcp30axx/WHELP2.ZIP
	install -D -d $(DSTDIR_BCP30AF)BIN/
	unzip -DD -o -d $(DSTDIR_BCP30AF)BIN/ $<

ARCHIVE_BCP30AF_WHEREIS:=BIOS.INC BIOSMAC.DOC DEMO1.BAT DOS.INC DOSMAC.DOC IASCIIZS.ASM IBIOS.MAC IBYTECPY.ASM IDELCHAR.ASM IDOS.INC IDOS.MAC IEXECDOS.ASM IFINDBYT.ASM IFINDFIL.ASM IFINDREP.ASM ILOCSTRG.ASM IMACROS.MAC IPARAM.ASM IPARSEFN.ASM ISKPWHIT.ASM IWHEREIS.ASM IWHGLOBL.INC IWRITEPS.ASM KBD.INC WHEREIS.DOC WHEREIS.MAK WHUSAGE.INC
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/TASM/WHEREIS/%,$(ARCHIVE_BCP30AF_WHEREIS))
$(patsubst %,$(DSTDIR_BCP30AF)EXAMPLES/TASM/WHEREIS/%,$(ARCHIVE_BCP30AF_WHEREIS)) &: osdisks/bcp30axx/WHEREIS.ZIP
	install -D -d $(DSTDIR_BCP30AF)EXAMPLES/TASM/WHEREIS/
	unzip -DD -o -d $(DSTDIR_BCP30AF)EXAMPLES/TASM/WHEREIS/ $<

ARCHIVE_BCP30AF_WINCLUDE:=BWCC.H CUSTCNTL.H DDE.H DRIVINIT.H WINDOWS.H WINDOWS.INC
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)INCLUDE/%,$(ARCHIVE_BCP30AF_WINCLUDE))
$(patsubst %,$(DSTDIR_BCP30AF)INCLUDE/%,$(ARCHIVE_BCP30AF_WINCLUDE)) &: osdisks/bcp30axx/WINCLUDE.ZIP
	install -D -d $(DSTDIR_BCP30AF)INCLUDE/
	unzip -DD -o -d $(DSTDIR_BCP30AF)INCLUDE/ $<

ARCHIVE_BCP30AF_WINLBSRC:=ABORT.C ASMMEM.ASM ASSERT.C BCRTL.DEF EASYWIN.CPP ERREXIT.C EWCONIO.C EWINPROC.CPP FARHEAP.CPP FHEAP.CPP FPERR.ASM FPINIT.ASM GDI.DEF HEAP.CPP H_CHKSTK.ASM IMPORT.MAK INDEP.MAK INSTDATA.CPP INT86.CAS INTDOS.CAS INTR.CAS IOCTL.CAS KERNEL.DEF KEYBOARD.DEF NECP.C PTABLE.ASM RTLDATA.CPP RTLMAIN.C SETARGV.C SETARGV0.C SETENV.C SETENVRN.C SETJMP.ASM SIGNAL.C SOUND.DEF SUBALLOC.CPP TASM.CFG TCDLL.CFG TURBOC.CFG USER.DEF WCFNCPTR.CPP WEP.C WIN87EM.DEF WINDLL.MAK WINLIB.MAK WINMAIN.C WINMEM.ASM WINOBJ.MAK WREALCVT.ASM WSCANTOD.ASM
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)CRTL/WINLIB/%,$(ARCHIVE_BCP30AF_WINLBSRC))
$(patsubst %,$(DSTDIR_BCP30AF)CRTL/WINLIB/%,$(ARCHIVE_BCP30AF_WINLBSRC)) &: osdisks/bcp30axx/WINLBSRC.ZIP
	install -D -d $(DSTDIR_BCP30AF)CRTL/WINLIB/
	unzip -DD -o -d $(DSTDIR_BCP30AF)CRTL/WINLIB/ $<

ARCHIVE_BCP30AF_WINLIB:=C0WC.OBJ C0WL.OBJ C0WM.OBJ C0WS.OBJ CRTLDLL.LIB CWC.LIB CWL.LIB CWM.LIB CWS.LIB MATHWC.LIB MATHWL.LIB MATHWM.LIB MATHWS.LIB
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)LIB/%,$(ARCHIVE_BCP30AF_WINLIB))
$(patsubst %,$(DSTDIR_BCP30AF)LIB/%,$(ARCHIVE_BCP30AF_WINLIB)) &: osdisks/bcp30axx/WINLIB.ZIP
	install -D -d $(DSTDIR_BCP30AF)LIB/
	unzip -DD -o -d $(DSTDIR_BCP30AF)LIB/ $<

ARCHIVE_BCP30AF_WLOBJ:=VERSION.OBJ
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/OBJECT/WL/%,$(ARCHIVE_BCP30AF_WLOBJ))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/OBJECT/WL/%,$(ARCHIVE_BCP30AF_WLOBJ)) &: osdisks/bcp30axx/WLOBJ.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/OBJECT/WL/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/OBJECT/WL/ $<

ARCHIVE_BCP30AF_WMOBJ:=VERSION.OBJ
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/OBJECT/WM/%,$(ARCHIVE_BCP30AF_WMOBJ))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/OBJECT/WM/%,$(ARCHIVE_BCP30AF_WMOBJ)) &: osdisks/bcp30axx/WMOBJ.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/OBJECT/WM/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/OBJECT/WM/ $<

ARCHIVE_BCP30AF_WSOBJ:=VERSION.OBJ
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)OWL/OBJECT/WS/%,$(ARCHIVE_BCP30AF_WSOBJ))
$(patsubst %,$(DSTDIR_BCP30AF)OWL/OBJECT/WS/%,$(ARCHIVE_BCP30AF_WSOBJ)) &: osdisks/bcp30axx/WSOBJ.ZIP
	install -D -d $(DSTDIR_BCP30AF)OWL/OBJECT/WS/
	unzip -DD -o -d $(DSTDIR_BCP30AF)OWL/OBJECT/WS/ $<

ARCHIVE_BCP30AF_XLIB:=BWCC.LIB EMU.LIB FP87.LIB GRAPHICS.LIB IMPORT.LIB MATHERR.C OVERLAY.LIB WILDARGS.OBJ
BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)LIB/%,$(ARCHIVE_BCP30AF_XLIB))
$(patsubst %,$(DSTDIR_BCP30AF)LIB/%,$(ARCHIVE_BCP30AF_XLIB)) &: osdisks/bcp30axx/XLIB.ZIP
	install -D -d $(DSTDIR_BCP30AF)LIB/
	unzip -DD -o -d $(DSTDIR_BCP30AF)LIB/ $<

BCP30AF_TARGETS:=$(BCP30AF_TARGETS) $(patsubst %,$(DSTDIR_BCP30AF)%,FILELIST.DOC README README.COM BIN/UNZIP.EXE)
$(DSTDIR_BCP30AF)FILELIST.DOC: osdisks/bcp30axx/FILELIST.DOC
	install -D $< $@
$(DSTDIR_BCP30AF)README: osdisks/bcp30axx/README
	install -D $< $@
$(DSTDIR_BCP30AF)README.COM: osdisks/bcp30axx/README.COM
	install -D $< $@
$(DSTDIR_BCP30AF)BIN/UNZIP.EXE: osdisks/bcp30axx/UNZIP.EXE
	install -D $< $@

.PHONY: prepare-bcp30af
prepare-bcp30af: $(BCP30AF_TARGETS)

