# TODO! --GM
#
# Microsoft MS-DOS 5.00a, 90mm 720K version
#
SRCDIR_DOS50A_DISKS:=packages/dos50a/
DISK_DOS50A_01:=8514.VI_ ANSI.SY_ AUTOEXEC.BAT COMMAND.COM CONFIG.SYS COUNTRY.SYS CV.COM DEBUG.EX_ DISPLAY.SY_ DOSKEY.CO_ EDLIN.EX_ EGA.CP_ EGA.SY_ EMM386.EX_ FASTOPEN.EX_ FDISK.EXE FORMAT.COM HIMEM.SY_ KEYB.COM KEYBOARD.SYS MEM.EX_ MIRROR.CO_ MODE.CO_ NLSFUNC.EXE RAMDRIVE.SY_ README.1ST SETUP.EXE SETUP.INI SETVER.EX_ SHARE.EX_ SMARTDRV.SY_ SYS.CO_ UNDELETE.EX_ UNFORMAT.COM XCOPY.EX_
DISK_DOS50A_02:=APPNOTES.TXT CGA.GR_ CGA.IN_ CGA.VI_ DOSHELP.HL_ DOSSHELL.CO_ DOSSHELL.EX_ DOSSHELL.HL_ DOSSWAP.EX_ EDIT.COM EDIT.HL_ EGA.GR_ EGA.IN_ EGA.VI_ EGAMONO.GR_ HELP.EX_ HERC.GR_ HERC.VI_ MONEY.BA_ MONO.GR_ MONO.IN_ MSHERC.CO_ PACKING.LST PRINT.EX_ QBASIC.EX_ QBASIC.HL_ RECOVER.EX_ VGA.GR_ VGA.VI_ VGAMONO.GR_
DISK_DOS50A_03:=4201.CP_ 4208.CP_ 5202.CP_ APPEND.EX_ ASSIGN.CO_ ATTRIB.EX_ BACKUP.EX_ CHKDSK.EX_ COMP.EX_ DISKCOMP.CO_ DISKCOPY.CO_ DRIVER.SY_ EXE2BIN.EX_ EXPAND.EXE FC.EX_ FIND.EX_ GORILLA.BA_ GRAFTABL.CO_ GRAPHICS.CO_ GRAPHICS.PR_ JOIN.EX_ LABEL.EX_ LCD.CP_ LOADFIX.CO_ MORE.CO_ NIBBLES.BA_ PRINTER.SY_ PRINTFIX.COM README.TXT REMLINE.BA_ REPLACE.EX_ RESTORE.EX_ SORT.EX_ SUBST.EX_ TREE.CO_ WINA20.38_



