#
# Microsoft C Professional Development System 6.0a, 5.25" 360K version
#
# WARNING: THIS DOES NOT MERGE CLEANLY.
# If we merge all the files together in ascending disk order,
# we end up with the OS/2 compiler executables instead of the DOS ones.
# This DOES NOT WORK AT ALL.
#
SRCDIR_MSC60A_DISKS:=packages/msc60a/
DISK_MSC60A_01:=C1.ER$$ C1.EX$$ C1L.EX$$ C2.EX$$ C23.ER$$ C2L.EX$$ C3L.EX$$ LIB.EX$$ PACKING.LST QCC.EX$$ README.DOC SETUP.EXE
DISK_MSC60A_02:=C1.EX$$ C1L.EX$$ C2.EX$$ C3.EX$$ CL.EX$$ CV.EX$$ FIXSHIFT.CO$$ HELP/QH.EX$$ HIMEM.SY$$ QCC.EX$$
DISK_MSC60A_03:=87.LI$$ BINMODE.OB$$ CLIBCR.LI$$ CLIBFA.LI$$ CLIBFP.LI$$ CRTCOM.LI$$ CRTDLL.OB$$ CRTDLL_I.OB$$ CRTEXE.OB$$ CRTLIB.OB$$ DLLINIT.OB$$ DLLTERM.OB$$ EM.LI$$ FILEINFO.OB$$ GRAPHICS.LI$$ HELP/CL.HL$$ HELP/HELPMAKE.EX$$ HELP/UTILS.HL$$ LIBH.LI$$ LLIBCMT.LI$$ LLIBCR.LI$$ LLIBFA.LI$$ LLIBFP.LI$$ MLIBCR.LI$$ MLIBFA.LI$$ MLIBFP.LI$$ PGCHART.LI$$ RMFIXUP.OB$$ SETARGV.OB$$ SGRAPHFA.LI$$ SLIBCR.LI$$ SLIBFA.LI$$ SLIBFP.LI$$ TXTONLY.OB$$ VARSTCK.OB$$
DISK_MSC60A_04:=CVPACK.EX$$ EXEHDR.EX$$ FONT/COURB.FO$$ FONT/HELVB.FO$$ FONT/MODERN.FO$$ FONT/ROMAN.FO$$ FONT/SCRIPT.FO$$ FONT/TMSRB.FO$$ HELP/LINK.HL$$ ILINK.EX$$ ILINKSTB.OV$$ IMPLIB.EX$$ INCLUDE/ASSERT.H$$ INCLUDE/BIOS.H$$ INCLUDE/CONIO.H$$ INCLUDE/CTYPE.H$$ INCLUDE/DIRECT.H$$ INCLUDE/DOS.H$$ INCLUDE/ERRNO.H$$ INCLUDE/FCNTL.H$$ INCLUDE/FLOAT.H$$ INCLUDE/GRAPH.H$$ INCLUDE/IO.H$$ INCLUDE/LIMITS.H$$ INCLUDE/LOCALE.H$$ INCLUDE/MALLOC.H$$ INCLUDE/MATH.H$$ INCLUDE/MEMORY.H$$ INCLUDE/PGCHART.H$$ INCLUDE/PROCESS.H$$ INCLUDE/SEARCH.H$$ INCLUDE/SETJMP.H$$ INCLUDE/SHARE.H$$ INCLUDE/SIGNAL.H$$ INCLUDE/STDARG.H$$ INCLUDE/STDDEF.H$$ INCLUDE/STDIO.H$$ INCLUDE/STDLIB.H$$ INCLUDE/STRING.H$$ INCLUDE/SYS/LOCKING.H$$ INCLUDE/SYS/STAT.H$$ INCLUDE/SYS/TIMEB.H$$ INCLUDE/SYS/TYPES.H$$ INCLUDE/SYS/UTIME.H$$ INCLUDE/TIME.H$$ INCLUDE/VARARGS.H$$ LINK.EX$$ MOUSE.CO$$ MSHERC.CO$$ NMAKE.EX$$ PATCH/PATCH320.DO$$ PATCH/RMRHS.EX$$ PATCH/SETRHS.EX$$ PATCH/STKPAT.BA$$ PATCH/STKPAT.SC$$ PWB/EXP.EX$$ PWB/EXT/EXT.DE$$ PWB/EXT/EXT.H$$ PWB/EXT/EXTHDR.OB$$ PWB/EXT/EXTSUP.LI$$ PWB/INI/BRIEF.IN$$ PWB/INI/TOOLS.PR$$ PWB/PWB.CO$$ PWB/PWBC.MX$$ PWB/PWBED.EX$$ PWB/PWBHELP.MX$$ PWB/PWBRMAKE.EX$$ PWB/PWBROWSE.MX$$ PWB/PWBUTILS.MX$$ PWB/RM.EX$$ PWB/UNDEL.EX$$ SOURCE/CHRTDEMO.C$$ SOURCE/CHRTDEMO.H$$ SOURCE/CHRTDEMO.MA$$ SOURCE/CHRTOPT.C$$ SOURCE/CHRTSUPT.C$$ SOURCE/FILTER.C$$ SOURCE/GRDEMO.C$$ SOURCE/GRDEMO.MA$$ SOURCE/INCLUDE.C$$ SOURCE/MENU.C$$ SOURCE/MENU.H$$ SOURCE/SAMPLES.DO$$ SOURCE/SNAP.C$$ SOURCE/SNAP.MA$$ SOURCE/SORTDEMO.C$$ SOURCE/SORTDEMO.MA$$ SOURCE/TURTLE.C$$ SOURCE/TURTLE.H$$ SOURCE/TXTFMT.C$$ STARTUP/CHKSTK.AS$$ STARTUP/CHKSUM.AS$$ STARTUP/CMACROS.IN$$ STARTUP/CRT0FP.AS$$ STARTUP/DOS/CRT0.AS$$ STARTUP/DOS/CRT0DAT.AS$$ STARTUP/DOS/CRT0MSG.AS$$ STARTUP/DOS/EXECMSG.AS$$ STARTUP/DOS/NMSGHDR.AS$$ STARTUP/DOS/NULBODY.LN$$ STARTUP/DOS/STDALLOC.AS$$ STARTUP/DOS/STDARGV.AS$$ STARTUP/DOS/STDENVP.AS$$ STARTUP/EMOEM.AS$$ STARTUP/FILE2.H$$ STARTUP/FMSGHDR.AS$$ STARTUP/HEAP.IN$$ STARTUP/MAKEFILE.$$ STARTUP/MSDOS.H$$ STARTUP/MSDOS.IN$$ STARTUP/NULBODY.C$$ STARTUP/OS2/CRT0.AS$$ STARTUP/OS2/CRT0DAT.AS$$ STARTUP/OS2/CRT0MSG.AS$$ STARTUP/OS2/NMSGHDR.AS$$ STARTUP/OS2/NULBODY.LN$$ STARTUP/OS2/STDALLOC.AS$$ STARTUP/OS2/STDARGV.AS$$ STARTUP/OS2/STDENVP.AS$$ STARTUP/RCHKSTK.AS$$ STARTUP/REGISTER.H$$ STARTUP/RTERR.IN$$ STARTUP/SETARGV.AS$$ STARTUP/STARTUP.BA$$ STARTUP/STARTUP.CM$$ STARTUP/STARTUP.DO$$ STARTUP/VERSION.IN$$ STARTUP/WILD.C$$ STARTUP/_FILE.C$$
DISK_MSC60A_05:=CDLLOBJS.CM$$ CDLLOBJS.DE$$ CDLLOBJS.LI$$ CDLLSUPP.LI$$ CL.ER$$ CL.EX$$ CL.MS$$ CLIBCP.LI$$ CVP.EX$$ GRTEXTP.LI$$ LLIBCDLL.LI$$ LLIBCP.LI$$ MGRAPHFA.LI$$ MGRAPHFP.LI$$ MLIBCP.LI$$ OS2.LI$$ PWB/EXT/EXTHDRP.OB$$ PWB/EXT/EXTHDRPD.OB$$ PWB/MSHELP.DL$$ PWB/PWB.EX$$ PWB/PWBC.PX$$ PWB/PWBHELP.PX$$ PWB/PWBROWSE.PX$$ SGRAPHFP.LI$$ SLIBCP.LI$$
DISK_MSC60A_06:=HELP/CLANG.HL$$ HELP/CV.HL$$ HELP/EXT.HL$$ HELP/PWB.HL$$ HELP/QH.HL$$ NMK.CO$$
DISK_MSC60A_07:=API.LI$$ APILMR.OB$$ BIND.EX$$ C3.EX$$ HELP/UTILERR.HL$$ INC11/BSE.H$$ INC11/BSEDEV.H$$ INC11/BSEDOS.H$$ INC11/BSEERR.H$$ INC11/BSESUB.H$$ INC11/OS2.H$$ INC11/OS2DEF.H$$ INC11/PM.H$$ INC11/PMAVIO.H$$ INC11/PMBITMAP.H$$ INC11/PMDEV.H$$ INC11/PMFONT.H$$ INC11/PMGPI.H$$ INC11/PMORD.H$$ INC11/PMPIC.H$$ INC11/PMSHL.H$$ INC11/PMSPL.H$$ INC11/PMWIN.H$$ INCLUDE/BSE.H$$ INCLUDE/BSEDEV.H$$ INCLUDE/BSEDOS.H$$ INCLUDE/BSEERR.H$$ INCLUDE/BSESUB.H$$ INCLUDE/OS2.H$$ INCLUDE/OS2DEF.H$$ INCLUDE/PM.H$$ INCLUDE/PMAVIO.H$$ INCLUDE/PMBITMAP.H$$ INCLUDE/PMDEV.H$$ INCLUDE/PMERR.H$$ INCLUDE/PMFONT.H$$ INCLUDE/PMGPI.H$$ INCLUDE/PMHELP.H$$ INCLUDE/PMMLE.H$$ INCLUDE/PMORD.H$$ INCLUDE/PMPIC.H$$ INCLUDE/PMSHL.H$$ INCLUDE/PMTYPES.H$$ INCLUDE/PMWIN.H$$ NMAKE.EX$$ OS2.LI$$ PWB/PWBUTILS.PX$$ RAMDRIVE.SY$$ RC.EX$$ RC.HL$$ RCPP.ER$$ RCPP.EX$$ SMARTDRV.SY$$
EXTRACT_MSC60A_DISKS:=\
	$(patsubst %,osdisks/cc01/%,$(DISK_MSC60A_01)) \
	$(patsubst %,osdisks/cc02/%,$(DISK_MSC60A_02)) \
	$(patsubst %,osdisks/cc03/%,$(DISK_MSC60A_03)) \
	$(patsubst %,osdisks/cc04/%,$(DISK_MSC60A_04)) \
	$(patsubst %,osdisks/cc05/%,$(DISK_MSC60A_05)) \
	$(patsubst %,osdisks/cc06/%,$(DISK_MSC60A_06)) \
	$(patsubst %,osdisks/cc07/%,$(DISK_MSC60A_07)) \
	#
MERGE_MSC60A_DISKS:=\
	$(sort \
		$(patsubst %,osdisks/ccxx/%,$(DISK_MSC60A_01)) \
		$(patsubst %,osdisks/ccxx/%,$(DISK_MSC60A_02)) \
		$(patsubst %,osdisks/ccxx/%,$(DISK_MSC60A_03)) \
		$(patsubst %,osdisks/ccxx/%,$(DISK_MSC60A_04)) \
		$(patsubst %,osdisks/ccxx/%,$(DISK_MSC60A_05)) \
		$(patsubst %,osdisks/ccxx/%,$(DISK_MSC60A_06)) \
		$(patsubst %,osdisks/ccxx/%,$(DISK_MSC60A_07)) \
	)

$(patsubst %,osdisks/cc01/%,$(DISK_MSC60A_01)) &: $(SRCDIR_MSC60A_DISKS)Disk1\ -\ Setup,\ Compiler\ 1.img
	(install -D -d osdisks/cc01/ && mcopy -n -D o -s -i "$<" :: osdisks/cc01/)
$(patsubst %,osdisks/cc02/%,$(DISK_MSC60A_02)) &: $(SRCDIR_MSC60A_DISKS)Disk2\ -\ Compiler\ 2.img
	(install -D -d osdisks/cc02/ && mcopy -n -D o -s -i "$<" :: osdisks/cc02/)
$(patsubst %,osdisks/cc03/%,$(DISK_MSC60A_03)) &: $(SRCDIR_MSC60A_DISKS)Disk3\ -\ Libraries.img
	(install -D -d osdisks/cc03/ && mcopy -n -D o -s -i "$<" :: osdisks/cc03/)
$(patsubst %,osdisks/cc04/%,$(DISK_MSC60A_04)) &: $(SRCDIR_MSC60A_DISKS)Disk4\ -\ Workbench\ Utilities.img
	(install -D -d osdisks/cc04/ && mcopy -n -D o -s -i "$<" :: osdisks/cc04/)
$(patsubst %,osdisks/cc05/%,$(DISK_MSC60A_05)) &: $(SRCDIR_MSC60A_DISKS)Disk5\ -\ Workbench\ Utilities\ for\ OS2.img
	(install -D -d osdisks/cc05/ && mcopy -n -D o -s -i "$<" :: osdisks/cc05/)
$(patsubst %,osdisks/cc06/%,$(DISK_MSC60A_06)) &: $(SRCDIR_MSC60A_DISKS)Disk6\ -\ Online\ Reference.img
	(install -D -d osdisks/cc06/ && mcopy -n -D o -s -i "$<" :: osdisks/cc06/)
$(patsubst %,osdisks/cc07/%,$(DISK_MSC60A_07)) &: $(SRCDIR_MSC60A_DISKS)Disk7\ -\ Libraries\ for\ OS2.img
	(install -D -d osdisks/cc07/ && mcopy -n -D o -s -i "$<" :: osdisks/cc07/)

$(MERGE_MSC60A_DISKS) &: $(EXTRACT_MSC60A_DISKS)
	install -D -d osdisks/ccxx/
	cp -r osdisks/cc01/* osdisks/ccxx/
	cp -r osdisks/cc02/* osdisks/ccxx/
	cp -r osdisks/cc03/* osdisks/ccxx/
	cp -r osdisks/cc04/* osdisks/ccxx/
	cp -r osdisks/cc05/* osdisks/ccxx/
	cp -r osdisks/cc06/* osdisks/ccxx/
	cp -r osdisks/cc07/* osdisks/ccxx/
