#
# Microsoft Windows 3.0 SDK, 90mm 720K version
#
SRCDIR_SDK30_DISKS:=packages/winsdk30/
DISK_SDK30_29:=INSTALL.EXE INSTALL.INF LIB.EXE README.TXT RESTOOLS/ATRM1111.FNT RESTOOLS/DIALOG.EXE RESTOOLS/FONTEDIT.EXE RESTOOLS/HC.EXE RESTOOLS/RC.EXE RESTOOLS/RCPP.ERR RESTOOLS/RCPP.EXE RESTOOLS/SDKPAINT.DAT RESTOOLS/VGASYS.FNT
DISK_SDK30_30:=ANALYSIS/HEAPWALK.EXE ANALYSIS/HOOK.DLL ANALYSIS/PROF.COM ANALYSIS/SHAKER.EXE ANALYSIS/SHOWHITS.EXE ANALYSIS/SPY.EXE ANALYSIS/SWAP.EXE ANALYSIS/VPROD.386 CONVERT/COMPRESS.EXE CONVERT/CONVBMP.EXE CONVERT/EXPAND.EXE CONVERT/MARK.EXE DBGTOOLS/CVW.HLP DBGTOOLS/D2N.BAT DBGTOOLS/MAPSYM.EXE DBGTOOLS/N2D.BAT DBGTOOLS/SWITCH.BAT DBGTOOLS/SYMDEB.EXE DBGTOOLS/WINDEBUG.386 DBGTOOLS/WINDEBUG.DLL RESTOOLS/SDKPAINT.EXE RESTOOLS/SDKTOOLS.GRP RESTOOLS/ZOOMIN.EXE
DISK_SDK30_31:=DBGTOOLS/CVW.EXE DBGTOOLS/WDEB386.EXE DEBUG/GDI.EXE DEBUG/KRNL286.EXE
DISK_SDK30_32:=DEBUG/GDI.SYM DEBUG/KERNEL.EXE DEBUG/KERNEL.SYM DEBUG/KRNL286.SYM DEBUG/KRNL386.EXE DEBUG/KRNL386.SYM DEBUG/USER.EXE DEBUG/USER.SYM NODEBUG/GDI.SYM NODEBUG/KERNEL.SYM NODEBUG/KRNL286.SYM NODEBUG/KRNL386.SYM NODEBUG/USER.SYM SKERNEL/SKERNEL.EXE SKERNEL/SKERNEL.SYM VGA.DRV WINSTUB/WINSTUB.EXE
DISK_SDK30_33:=CLIB/DLLCW.BAT CLIB/LIBCW.BAT CLIB/LIBH.LIB CLIB/MDLLCW0.LIB CLIB/MLIBCW.LIB CLIB/MLIBFAW.LIB CLIB/MLIBFPW.LIB CLIB/SDLLCW0.LIB CLIB/SLIBCW.LIB CLIB/SLIBFAW.LIB CLIB/SLIBFPW.LIB CLIB/WINCDLL.BLD WLIB/CNOCRT.LIB WLIB/CNOCRTD.LIB WLIB/LIBENTRY.ASM WLIB/LIBENTRY.OBJ WLIB/LIBW.LIB WLIB/LNOCRT.LIB WLIB/LNOCRTD.LIB WLIB/MNOCRT.LIB WLIB/MNOCRTD.LIB WLIB/SNOCRT.LIB WLIB/SNOCRTD.LIB WLIB/WIN87EM.LIB
DISK_SDK30_34:=CLIB/CDLLCW0.LIB CLIB/CLIBCW.LIB CLIB/CLIBFAW.LIB CLIB/CLIBFPW.LIB CLIB/LDLLCW0.LIB CLIB/LLIBCW.LIB CLIB/LLIBFAW.LIB CLIB/LLIBFPW.LIB NETAPI.TXT PWBINFO.WRI README.WRI TIPS.TXT WINMEM32/WINMEM32.DLL WINMEM32/WINMEM32.H WINMEM32/WINMEM32.LIB
DISK_SDK30_35:=BITMAP/BITMAP BITMAP/BITMAP.C BITMAP/BITMAP.DEF BITMAP/BITMAP.H BITMAP/BITMAP.RC BITMAP/CAT.BMP BITMAP/DOG.BMP BITMAP/SELECT.DLL BITMAP/SELECT.H BITMAP/SELECT.LIB CINC/ASSERT.H CINC/BIOS.H CINC/CONIO.H CINC/CTYPE.H CINC/DIRECT.H CINC/DOS.H CINC/ERRNO.H CINC/FCNTL.H CINC/FLOAT.H CINC/IO.H CINC/LIMITS.H CINC/LOCALE.H CINC/MALLOC.H CINC/MATH.H CINC/MEMORY.H CINC/PROCESS.H CINC/SEARCH.H CINC/SETJMP.H CINC/SHARE.H CINC/SIGNAL.H CINC/STDARG.H CINC/STDDEF.H CINC/STDIO.H CINC/STDLIB.H CINC/STRING.H CINC/SYS/LOCKING.H CINC/SYS/STAT.H CINC/SYS/TIMEB.H CINC/SYS/TYPES.H CINC/SYS/UTIME.H CINC/TIME.H CINC/VARARGS.H CLIPTEXT/CLIPTEXT CLIPTEXT/CLIPTEXT.C CLIPTEXT/CLIPTEXT.DEF CLIPTEXT/CLIPTEXT.H CLIPTEXT/CLIPTEXT.RC CLOCK/CLOCK CLOCK/CLOCK.C CLOCK/CLOCK.DEF CLOCK/CLOCK.DLG CLOCK/CLOCK.H CLOCK/CLOCK.ICO CLOCK/CLOCK.RC CLOCK/CLOCKDAT.ASM CLOCK/CLOCKDAT.OBJ CLOCK/GETTIME.ASM CLOCK/GETTIME.OBJ CURSOR/BULLSEYE.CUR CURSOR/CURSOR CURSOR/CURSOR.C CURSOR/CURSOR.DEF CURSOR/CURSOR.H CURSOR/CURSOR.RC DDE/CLIDATA.C DDE/CLIDDE.C DDE/CLIENT DDE/CLIENT.C DDE/CLIENT.DEF DDE/CLIENT.DLG DDE/CLIENT.H DDE/CLIENT.RC DDE/CLIRES.H DDE/SERVDATA.C DDE/SERVDDE.C DDE/SERVER DDE/SERVER.C DDE/SERVER.DEF DDE/SERVER.H DDE/SERVER.RC DDE/SERVRES.H DEFPROCS/DEFDLG.C DEFPROCS/DEFWND.C EDITCNTL/EDITCNTL EDITCNTL/EDITCNTL.C EDITCNTL/EDITCNTL.DEF EDITCNTL/EDITCNTL.H EDITCNTL/EDITCNTL.RC EDITFILE/EDITFILE EDITFILE/EDITFILE.C EDITFILE/EDITFILE.DEF EDITFILE/EDITFILE.H EDITFILE/EDITFILE.RC EDITMENU/EDITMENU EDITMENU/EDITMENU.C EDITMENU/EDITMENU.DEF EDITMENU/EDITMENU.H EDITMENU/EDITMENU.RC FILEOPEN/FILEOPEN FILEOPEN/FILEOPEN.C FILEOPEN/FILEOPEN.DEF FILEOPEN/FILEOPEN.H FILEOPEN/FILEOPEN.RC GENERIC/GENERIC GENERIC/GENERIC.C GENERIC/GENERIC.DEF GENERIC/GENERIC.H GENERIC/GENERIC.RC INC/CMACROS.INC INC/CUSTCNTL.H INC/DDE.H INC/DRIVINIT.H INC/WINDOWS.H INC/WINDOWS.INC
DISK_SDK30_36:=HELPEX/BULLET.BMP HELPEX/CHKBOFF.BMP HELPEX/CHKBON.BMP HELPEX/CODEC.BMP HELPEX/CONTINUE.BMP HELPEX/DONE.BMP HELPEX/HELP.CUR HELPEX/HELPEX HELPEX/HELPEX.C HELPEX/HELPEX.DEF HELPEX/HELPEX.DLG HELPEX/HELPEX.H HELPEX/HELPEX.HPJ HELPEX/HELPEX.RC HELPEX/HELPEX.RTF HELPEX/HELPICON.BMP HELPEX/HELPIDS.H HELPEX/KEYS.RTF HELPEX/MAX2ICON.BMP HELPEX/MOUSE.BMP HELPEX/TERMS.RTF HELPEX/WINWORD.BMP ICON/ICON ICON/ICON.C ICON/ICON.DEF ICON/ICON.H ICON/ICON.RC ICON/MYICON.ICO INPUT/INPUT INPUT/INPUT.C INPUT/INPUT.DEF INPUT/INPUT.H INPUT/INPUT.RC MEMORY/MEMORY MEMORY/MEMORY.DEF MEMORY/MEMORY.H MEMORY/MEMORY.RC MEMORY/MEMORY1.C MEMORY/MEMORY2.C MEMORY/MEMORY3.C MEMORY/MEMORY4.C MENU/CHECKOFF.BMP MENU/CHECKON.BMP MENU/MENU MENU/MENU.C MENU/MENU.DEF MENU/MENU.DLG MENU/MENU.H MENU/MENU.ICO MENU/MENU.RC MULTIPAD/MP300.ICO MULTIPAD/MPFILE.C MULTIPAD/MPFIND.C MULTIPAD/MPINIT.C MULTIPAD/MPOPEN.C MULTIPAD/MPPRINT.C MULTIPAD/MULTIPAD MULTIPAD/MULTIPAD.C MULTIPAD/MULTIPAD.DEF MULTIPAD/MULTIPAD.DLG MULTIPAD/MULTIPAD.H MULTIPAD/MULTIPAD.LNK MULTIPAD/MULTIPAD.RC MULTIPAD/NOTE300.ICO MYPAL/MYPAL MYPAL/MYPAL.C MYPAL/MYPAL.DEF MYPAL/MYPAL.H MYPAL/MYPAL.ICO MYPAL/MYPAL.RC OUTPUT/OUTPUT OUTPUT/OUTPUT.C OUTPUT/OUTPUT.DEF OUTPUT/OUTPUT.H OUTPUT/OUTPUT.RC OWNCOMBO/OWNCOMBO OWNCOMBO/OWNCOMBO.C OWNCOMBO/OWNCOMBO.DEF OWNCOMBO/OWNCOMBO.DLG OWNCOMBO/OWNCOMBO.H OWNCOMBO/OWNCOMBO.ICO OWNCOMBO/OWNCOMBO.RC OWNCOMBO/README.TXT PRNTFILE/PRNTFILE PRNTFILE/PRNTFILE.C PRNTFILE/PRNTFILE.DEF PRNTFILE/PRNTFILE.H PRNTFILE/PRNTFILE.RC RAINBOW/LIBENTRY.ASM RAINBOW/LIBENTRY.OBJ RAINBOW/RAINBOW RAINBOW/RAINBOW.C RAINBOW/RAINBOW.DEF RAINBOW/RAINBOW.DLG RAINBOW/RAINBOW.H RAINBOW/RAINBOW.RC SELECT/DEMO SELECT/DEMO.C SELECT/DEMO.DEF SELECT/DEMO.H SELECT/DEMO.RC SELECT/LIBENTRY.ASM SELECT/LIBENTRY.OBJ SELECT/SELECT SELECT/SELECT.C SELECT/SELECT.DEF SELECT/SELECT.H SHOWDIB/DIB.C SHOWDIB/DLGOPEN.C SHOWDIB/DLGOPEN.DLG SHOWDIB/DLGOPENA.ASM SHOWDIB/DLGOPENA.OBJ SHOWDIB/DRAWDIB.C SHOWDIB/PRINT.C SHOWDIB/PRINT.DLG SHOWDIB/SHOWDIB SHOWDIB/SHOWDIB.C SHOWDIB/SHOWDIB.DEF SHOWDIB/SHOWDIB.DLG SHOWDIB/SHOWDIB.H SHOWDIB/SHOWDIB.ICO SHOWDIB/SHOWDIB.RC SHOWFONT/CFONT.C SHOWFONT/SHOWFONT SHOWFONT/SHOWFONT.C SHOWFONT/SHOWFONT.DEF SHOWFONT/SHOWFONT.H SHOWFONT/SHOWFONT.ICO SHOWFONT/SHOWFONT.RC TTY/TTY TTY/TTY.C TTY/TTY.DEF TTY/TTY.DLG TTY/TTY.H TTY/TTY.ICO TTY/TTY.RC TTY/TTY.TXT TTY/WSTDIO.C TTY/WSTDIO.H TTY/WSTDIO.TXT
DISK_SDK30_37:=HELPADV/SDKADV.HL$$
DISK_SDK30_38:=HELPWIN/SDKWIN.HL$$
EXTRACT_SDK30_DISKS:=\
	$(patsubst %,osdisks/sdk29/%,$(DISK_SDK30_29)) \
	$(patsubst %,osdisks/sdk30/%,$(DISK_SDK30_30)) \
	$(patsubst %,osdisks/sdk31/%,$(DISK_SDK30_31)) \
	$(patsubst %,osdisks/sdk32/%,$(DISK_SDK30_32)) \
	$(patsubst %,osdisks/sdk33/%,$(DISK_SDK30_33)) \
	$(patsubst %,osdisks/sdk34/%,$(DISK_SDK30_34)) \
	$(patsubst %,osdisks/sdk35/%,$(DISK_SDK30_35)) \
	$(patsubst %,osdisks/sdk36/%,$(DISK_SDK30_36)) \
	$(patsubst %,osdisks/sdk37/%,$(DISK_SDK30_37)) \
	$(patsubst %,osdisks/sdk38/%,$(DISK_SDK30_38)) \
	#
MERGE_SDK30_DISKS:=\
	$(sort \
		$(patsubst %,osdisks/sdkxx/%,$(DISK_SDK30_29)) \
		$(patsubst %,osdisks/sdkxx/%,$(DISK_SDK30_30)) \
		$(patsubst %,osdisks/sdkxx/%,$(DISK_SDK30_31)) \
		$(patsubst %,osdisks/sdkxx/%,$(DISK_SDK30_32)) \
		$(patsubst %,osdisks/sdkxx/%,$(DISK_SDK30_33)) \
		$(patsubst %,osdisks/sdkxx/%,$(DISK_SDK30_34)) \
		$(patsubst %,osdisks/sdkxx/%,$(DISK_SDK30_35)) \
		$(patsubst %,osdisks/sdkxx/%,$(DISK_SDK30_36)) \
		$(patsubst %,osdisks/sdkxx/%,$(DISK_SDK30_37)) \
		$(patsubst %,osdisks/sdkxx/%,$(DISK_SDK30_38)) \
	)

$(patsubst %,osdisks/sdk29/%,$(DISK_SDK30_29)) &: $(SRCDIR_SDK30_DISKS)Development\ Tools\ 1\ (050-151-029).img
	(install -D -d osdisks/sdk29/ && mcopy -n -D o -s -i "$<" :: osdisks/sdk29/)
$(patsubst %,osdisks/sdk30/%,$(DISK_SDK30_30)) &: $(SRCDIR_SDK30_DISKS)Development\ Tools\ 2\ -\ Debug\ Tools\ 1\ (050-151-030).img
	(install -D -d osdisks/sdk30/ && mcopy -n -D o -s -i "$<" :: osdisks/sdk30/)
$(patsubst %,osdisks/sdk31/%,$(DISK_SDK30_31)) &: $(SRCDIR_SDK30_DISKS)Debug\ Tools\ 2\ -\ Debug\ Files\ 1\ (050-151-031).img
	(install -D -d osdisks/sdk31/ && mcopy -n -D o -s -i "$<" :: osdisks/sdk31/)
$(patsubst %,osdisks/sdk32/%,$(DISK_SDK30_32)) &: $(SRCDIR_SDK30_DISKS)Debug\ Files\ 2\ (050-151-032).img
	(install -D -d osdisks/sdk32/ && mcopy -n -D o -s -i "$<" :: osdisks/sdk32/)
$(patsubst %,osdisks/sdk33/%,$(DISK_SDK30_33)) &: $(SRCDIR_SDK30_DISKS)Link\ Libraries\ 1\ (050-151-033).img
	(install -D -d osdisks/sdk33/ && mcopy -n -D o -s -i "$<" :: osdisks/sdk33/)
$(patsubst %,osdisks/sdk34/%,$(DISK_SDK30_34)) &: $(SRCDIR_SDK30_DISKS)Link\ Libraries\ 2\ (050-151-034).img
	(install -D -d osdisks/sdk34/ && mcopy -n -D o -s -i "$<" :: osdisks/sdk34/)
$(patsubst %,osdisks/sdk35/%,$(DISK_SDK30_35)) &: $(SRCDIR_SDK30_DISKS)Include\ Files,\ Sample\ Source\ Code\ 1\ (050-151-035).img
	(install -D -d osdisks/sdk35/ && mcopy -n -D o -s -i "$<" :: osdisks/sdk35/)
$(patsubst %,osdisks/sdk36/%,$(DISK_SDK30_36)) &: $(SRCDIR_SDK30_DISKS)Sample\ Source\ Code\ 2\ (050-151-036).img
	(install -D -d osdisks/sdk36/ && mcopy -n -D o -s -i "$<" :: osdisks/sdk36/)
$(patsubst %,osdisks/sdk37/%,$(DISK_SDK30_37)) &: $(SRCDIR_SDK30_DISKS)Online\ Reference\ (Advisor\ Format)\ (050-151-037).img
	(install -D -d osdisks/sdk37/ && mcopy -n -D o -s -i "$<" :: osdisks/sdk37/)
$(patsubst %,osdisks/sdk38/%,$(DISK_SDK30_38)) &: $(SRCDIR_SDK30_DISKS)Online\ Reference\ (Windows\ Help\ Format)\ (050-151-038).img
	(install -D -d osdisks/sdk38/ && mcopy -n -D o -s -i "$<" :: osdisks/sdk38/)

$(MERGE_SDK30_DISKS) &: $(EXTRACT_SDK30_DISKS)
	install -D -d osdisks/sdkxx/
	cp -r osdisks/sdk29/* osdisks/sdkxx/
	cp -r osdisks/sdk30/* osdisks/sdkxx/
	cp -r osdisks/sdk31/* osdisks/sdkxx/
	cp -r osdisks/sdk32/* osdisks/sdkxx/
	cp -r osdisks/sdk33/* osdisks/sdkxx/
	cp -r osdisks/sdk34/* osdisks/sdkxx/
	cp -r osdisks/sdk35/* osdisks/sdkxx/
	cp -r osdisks/sdk36/* osdisks/sdkxx/
	cp -r osdisks/sdk37/* osdisks/sdkxx/
	cp -r osdisks/sdk38/* osdisks/sdkxx/
