#
# Microsoft Windows 3.0a, 90mm 720K version
#
SRCDIR_WIN30A_DISKS:=packages/win30a/
DISK_WIN30A_01:=GDI.EXE KERNEL.EXE SETUP.EXE SETUP.HLP SETUP.INF USER.EXE WIN.CNF WINHELP.EXE WINHELP.HLP WINVER
DISK_WIN30A_02:=8514.DRV 8514FIX.FON 8514OEM.FON 8514SYS.FON CGA.DRV CGAFIX.FON CGALOGO.LGO CGALOGO.RLE CGAOEM.FON CGASYS.FON COMM.DRV CONTROL.INI EGA.DRV EGAFIX.FON EGAHIBW.DRV EGALOGO.LGO EGALOGO.RLE EGAMONO.DRV EGAMONO.LGO EGAMONO.RLE EGAOEM.FON EGASYS.FON EMM386.SY$$ EXPAND.EXE HERCLOGO.LGO HERCLOGO.RLE HERCULES.DRV HPMOUSE.DRV HPSYSTEM.DRV KBDBE.DLL KBDCA.DLL KBDDA.DLL KBDDV.DLL KBDFI.DLL KBDFR.DLL KBDGR.DLL KBDHP.DRV KBDIC.DLL KBDIT.DLL KBDLA.DLL KBDMOUSE.DRV KBDNE.DLL KBDNO.DLL KBDOLI.DRV KBDPO.DLL KBDSF.DLL KBDSG.DLL KBDSP.DLL KBDSW.DLL KBDUK.DLL KBDUS.DLL KBDUSX.DLL KEYBOARD.DRV LANGDUT.DLL LANGENG.DLL LANGFRN.DLL LANGGER.DLL LANGSCA.DLL LANGSPA.DLL LANMAN.DRV LMOUSE.DRV LZEXPAND.DLL MOUSE.DRV MSMOUSE1.DRV MSMOUSE2.DRV MSNET.DRV NETWARE.DRV NOMOUSE.DRV OLIBW.DRV PLASMA.DRV RAMDRIVE.SY$$ SMARTDRV.SY$$ SOUND.DRV SV400A.DRV SYSTEM.DRV SYSTEM.SRC TOSHWIN.VCD V7VGA.DRV VGA.DRV VGA850.FON VGA860.FON VGA861.FON VGA863.FON VGA865.FON VGAFIX.FON VGALOGO.LGO VGALOGO.RLE VGAMONO.DRV VGAOEM.FON VGASYS.FON WIN.SRC WINVER XLAT850.BIN XLAT860.BIN XLAT861.BIN XLAT863.BIN XLAT865.BIN
DISK_WIN30A_03:=CALC.EXE CALENDAR.EXE CARDFILE.EXE CONTROL.EXE DIGITAL.FON MSDOS.EXE NOTEPAD.EXE PBRUSH.EXE PIFEDIT.EXE PRINTMAN.EXE PROGMAN.EXE RECORDER.DLL RECORDER.EXE REVERSI.EXE SOL.EXE SYSEDIT.EXE WIN87EM.DLL WINFILE.EXE WINOLDAP.MOD WRITE.EXE
DISK_WIN30A_04:=CALC.HLP CALENDAR.HLP CLIPBRD.EXE CLIPBRD.HLP CLOCK.EXE CONTROL.HLP KRNL386.EXE NOTEPAD.HLP PBRUSH.DLL PBRUSH.HLP PIFEDIT.HLP PRINTMAN.HLP PROGMAN.HLP RECORDER.HLP REVERSI.HLP SOL.HLP SWAPFILE.EXE TASKMAN.EXE TERMINAL.EXE TERMINAL.HLP WIN386.EXE WIN386.PS2 WINFILE.HLP WINOA386.MOD WRITE.HLP
DISK_WIN30A_05:=3270.TXT 8514.GR3 BANINST.386 BOXES.BMP CARDFILE.HLP CGA.GR2 CGA.GR3 CGA40850.FON CGA40WOA.FON CGA80850.FON CGA80WOA.FON CHESS.BMP COURD.FON CR12RPA.PJF DOSX.EXE EGA.GR3 EGA.SY$$ EGA40850.FON EGA40WOA.FON EGA80850.FON EGA80WOA.FON EGACOLOR.GR2 EGAMONO.GR2 HELVD.FON HELVF.FON HERC.GR3 HERC850.FON HERCULES.GR2 HERCWOA.FON HIMEM.SY$$ HPEBIOS.386 KRNL286.EXE LANMAN.HLP LANMAN10.386 LG08RPA.PJF MOUSE.COM MOUSE.SY$$ MOUSEHP.COM MOUSEHP.SY$$ NETWARE.HLP NETWORKS.TXT NWPOPUP.EXE OLIGRAB.GR2 PAPER.BMP PLASMA.GR3 PRINTERS.TXT PYRAMID.BMP README.TXT SV400A.GR2 SYMBOLB.FON SYMBOLE.FON SYSINI.TXT SYSINI2.TXT SYSINI3.TXT TMSRB.FON TMSRD.FON TTY.DRV TTY.HLP V7VGA.GR3 VDD8514.386 VDDCGA.386 VDDCT441.386 VDDHERC.386 VGA.GR3 VGACOLOR.GR2 VGAMONO.GR2 VGAMONO.GR3 VIPX.386 VNETWARE.386 WEAVE.BMP WININI.TXT WININI2.TXT WINOA286.MOD
DISK_WIN30A_06:=CANONIII.DRV COURA.FON COURB.FON COURC.FON COURE.FON COURF.FON GENDRV.EXE HELVA.FON HELVB.FON HELVC.FON HELVE.FON IBM4019.DRV IBMCOLOR.DRV LBP8II.DRV LG12RPA.PJF MODERN.FON OLIPRINT.DRV PAINTJET.DRV PAINTJET.HLP PSCRIPT.DRV PSCRIPT.HLP ROMAN.FON SCRIPT.FON SF4019.EXE SYMBOLA.FON SYMBOLF.FON TMSRA.FON TMSRC.FON TMSRE.FON TMSRF.FON
DISK_WIN30A_07:=123.PIF CITOH.DRV DESKJET.DRV DESKJET.HLP DM600.DRV EPSON24.DRV EPSON9.DRV FINSTALL.DLL FINSTALL.HLP FUJIMTRX.DRV HPPCL.DRV HPPCL.HLP HPPCL5A.DRV HPPLOT.DRV IBMGRX.DRV NEC24PIN.DRV OKI24.DRV OKI9.DRV OKI9IBM.DRV OLIPRIN2.DRV PROPRINT.DRV PROPRN24.DRV QWIII.DRV TH760.DRV THINKJET.DRV TI850.DRV TOSHIBA.DRV
EXTRACT_WIN30A_DISKS:=\
	$(patsubst %,osdisks/win01/%,$(DISK_WIN30A_01)) \
	$(patsubst %,osdisks/win02/%,$(DISK_WIN30A_02)) \
	$(patsubst %,osdisks/win03/%,$(DISK_WIN30A_03)) \
	$(patsubst %,osdisks/win04/%,$(DISK_WIN30A_04)) \
	$(patsubst %,osdisks/win05/%,$(DISK_WIN30A_05)) \
	$(patsubst %,osdisks/win06/%,$(DISK_WIN30A_06)) \
	$(patsubst %,osdisks/win07/%,$(DISK_WIN30A_07)) \
	#
MERGE_WIN30A_DISKS:=\
	$(sort \
		$(patsubst %,osdisks/winxx/%,$(DISK_WIN30A_01)) \
		$(patsubst %,osdisks/winxx/%,$(DISK_WIN30A_02)) \
		$(patsubst %,osdisks/winxx/%,$(DISK_WIN30A_03)) \
		$(patsubst %,osdisks/winxx/%,$(DISK_WIN30A_04)) \
		$(patsubst %,osdisks/winxx/%,$(DISK_WIN30A_05)) \
		$(patsubst %,osdisks/winxx/%,$(DISK_WIN30A_06)) \
		$(patsubst %,osdisks/winxx/%,$(DISK_WIN30A_07)) \
	)

$(patsubst %,osdisks/win01/%,$(DISK_WIN30A_01)) &: $(SRCDIR_WIN30A_DISKS)DISK01.IMG
	(install -D -d osdisks/win01/ && mcopy -n -D o -s -i "$<" :: osdisks/win01/)
$(patsubst %,osdisks/win02/%,$(DISK_WIN30A_02)) &: $(SRCDIR_WIN30A_DISKS)DISK02.IMG
	(install -D -d osdisks/win02/ && mcopy -n -D o -s -i "$<" :: osdisks/win02/)
$(patsubst %,osdisks/win03/%,$(DISK_WIN30A_03)) &: $(SRCDIR_WIN30A_DISKS)DISK03.IMG
	(install -D -d osdisks/win03/ && mcopy -n -D o -s -i "$<" :: osdisks/win03/)
$(patsubst %,osdisks/win04/%,$(DISK_WIN30A_04)) &: $(SRCDIR_WIN30A_DISKS)DISK04.IMG
	(install -D -d osdisks/win04/ && mcopy -n -D o -s -i "$<" :: osdisks/win04/)
$(patsubst %,osdisks/win05/%,$(DISK_WIN30A_05)) &: $(SRCDIR_WIN30A_DISKS)DISK05.IMG
	(install -D -d osdisks/win05/ && mcopy -n -D o -s -i "$<" :: osdisks/win05/)
$(patsubst %,osdisks/win06/%,$(DISK_WIN30A_06)) &: $(SRCDIR_WIN30A_DISKS)DISK06.IMG
	(install -D -d osdisks/win06/ && mcopy -n -D o -s -i "$<" :: osdisks/win06/)
$(patsubst %,osdisks/win07/%,$(DISK_WIN30A_07)) &: $(SRCDIR_WIN30A_DISKS)DISK07.IMG
	(install -D -d osdisks/win07/ && mcopy -n -D o -s -i "$<" :: osdisks/win07/)

$(MERGE_WIN30A_DISKS) &: $(EXTRACT_WIN30A_DISKS)
	install -D -d osdisks/winxx/
	cp -r osdisks/win01/* osdisks/winxx/
	cp -r osdisks/win02/* osdisks/winxx/
	cp -r osdisks/win03/* osdisks/winxx/
	cp -r osdisks/win04/* osdisks/winxx/
	cp -r osdisks/win05/* osdisks/winxx/
	cp -r osdisks/win06/* osdisks/winxx/
	cp -r osdisks/win07/* osdisks/winxx/
